
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-10T13:22:41-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "86f4f899f25477d2949375c3436658669dd536a4",
 "version": "2.47.0rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
