# coding: utf-8

"""
    seqq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, Field
from typing import Any, ClassVar, Dict, List, Optional
from seqq.models.v1alpha_blastn import V1alphaBlastn
from typing import Optional, Set
from typing_extensions import Self

class V1alphaStrategy(BaseModel):
    """
    V1alphaStrategy
    """ # noqa: E501
    blastn: Optional[V1alphaBlastn] = None
    blastp: Optional[Dict[str, Any]] = Field(default=None, description="Blastp is a blastp search.")
    blastx: Optional[Dict[str, Any]] = Field(default=None, description="Blastp is a blastp search.")
    tblastn: Optional[Dict[str, Any]] = Field(default=None, description="Tblastn is a tblastn search.")
    tblastx: Optional[Dict[str, Any]] = Field(default=None, description="Tblastx is a tblastx search.")
    __properties: ClassVar[List[str]] = ["blastn", "blastp", "blastx", "tblastn", "tblastx"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of V1alphaStrategy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of blastn
        if self.blastn:
            _dict['blastn'] = self.blastn.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of V1alphaStrategy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "blastn": V1alphaBlastn.from_dict(obj["blastn"]) if obj.get("blastn") is not None else None,
            "blastp": obj.get("blastp"),
            "blastx": obj.get("blastx"),
            "tblastn": obj.get("tblastn"),
            "tblastx": obj.get("tblastx")
        })
        return _obj


