
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: aio.run.checker:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"Async checker definitions"',
    'install_requires': (
        'aio.run.runner>=0.3.4',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
aio.run.checker
===============

Async checker definitions.
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'aio.run.checker',
    'namespace_packages': (
    ),
    'package_data': {
        'aio.run.checker': (
            'py.typed',
        ),
    },
    'packages': (
        'aio.run.checker',
    ),
    'python_requires': '>=3.10.0',
    'url': 'https://github.com/envoyproxy/toolshed/tree/main/aio.run.checker',
    'version': '0.5.8',
})
