
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T13:16:08+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "fd4f2467a56c5032f6a8d8fd5414be68ae2285a0",
 "version": "4.0.0a5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
