# Generated by Django 4.0.8 on 2023-01-24 02:52

# Django
from django.db import migrations, models

# EVE Uni Member Tools
# AA EVE Uni Core
import membertools.models


class Migration(migrations.Migration):

    dependencies = [
        ("membertools", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TitleFilter",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="The filter description that is shown to end users.",
                        max_length=500,
                    ),
                ),
                (
                    "applied_titles",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Titles currently applied to main character.",
                        related_name="+",
                        to="membertools.applicationtitle",
                    ),
                ),
                (
                    "awarded_titles",
                    models.ManyToManyField(
                        default=membertools.models._get_app_title_all,
                        help_text="Titles awarded to the member.",
                        related_name="+",
                        to="membertools.applicationtitle",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
