# This file was auto-generated by Fern from our API Definition.

import typing
from .card_rcs import CardRcs
from .sms import Sms
from .basic_rcs import BasicRcs
from .media_rcs import MediaRcs
from .carousel_rcs import CarouselRcs

SendMessageRequest = typing.Union[CardRcs, Sms, BasicRcs, MediaRcs, CarouselRcs]
