# coding: utf-8

"""
    seqq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seqq.models.blastn_task import BlastnTask

class TestBlastnTask(unittest.TestCase):
    """BlastnTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBlastnTask(self):
        """Test BlastnTask"""
        # inst = BlastnTask()

if __name__ == '__main__':
    unittest.main()
