
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T17:25:36+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "c01ea574a424c5f07d50479c71c7d3c996b861a6",
 "version": "1.0.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
