
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T12:51:52-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "d3ab2e69ada3d367aa9a334796fd2d4f3f2bbb36",
 "version": "2.47.0rc4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
