
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-10T16:35:27-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e8cd03b37f8abeb3d77ca0e7b0c2207b4b4febdc",
 "version": "3.0.9.dev1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
