# coding: utf-8

"""
    seqq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seqq.models.v1alpha_create_record_request import V1alphaCreateRecordRequest

class TestV1alphaCreateRecordRequest(unittest.TestCase):
    """V1alphaCreateRecordRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1alphaCreateRecordRequest:
        """Test V1alphaCreateRecordRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1alphaCreateRecordRequest`
        """
        model = V1alphaCreateRecordRequest()
        if include_optional:
            return V1alphaCreateRecordRequest(
                collection = '',
                record_id = '',
                record = seqq.models.v1alpha_record.v1alphaRecord(
                    name = '', 
                    collection = '', 
                    sequence = '', 
                    code = 'CODE_UNSPECIFIED', 
                    taxonomy_id = '', 
                    create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    etag = '', 
                    description = '', )
            )
        else:
            return V1alphaCreateRecordRequest(
                collection = '',
                record_id = '',
                record = seqq.models.v1alpha_record.v1alphaRecord(
                    name = '', 
                    collection = '', 
                    sequence = '', 
                    code = 'CODE_UNSPECIFIED', 
                    taxonomy_id = '', 
                    create_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    etag = '', 
                    description = '', ),
        )
        """

    def testV1alphaCreateRecordRequest(self):
        """Test V1alphaCreateRecordRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
