
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T12:33:50+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "5c0029478a119f71cb07e7e013b4cdda665c172b",
 "version": "2.4.39"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
