
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-09T17:17:23-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "cdf2606f42d217b33dfe047f50e5998dc4b2dd7e",
 "version": "0.34.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
