# Generated by Django 4.2.3 on 2023-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djx_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthcredentials',
            name='access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='oauthcredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
