# Generated by Django 5.0.1 on 2024-02-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djx_account', '0003_user_birth_date_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
