# coding: utf-8

"""
    Orbital transfer API

    Orbital transfer API

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from orbital_transfer.models.time_stamped_pv_coordinates import TimeStampedPVCoordinates

class TestTimeStampedPVCoordinates(unittest.TestCase):
    """TimeStampedPVCoordinates unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TimeStampedPVCoordinates:
        """Test TimeStampedPVCoordinates
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TimeStampedPVCoordinates`
        """
        model = TimeStampedPVCoordinates()
        if include_optional:
            return TimeStampedPVCoordinates(
                var_date = '',
                position = orbital_transfer.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                velocity = orbital_transfer.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, ),
                acceleration = orbital_transfer.models.vector3_d.Vector3D(
                    x = 1.337, 
                    y = 1.337, 
                    z = 1.337, )
            )
        else:
            return TimeStampedPVCoordinates(
        )
        """

    def testTimeStampedPVCoordinates(self):
        """Test TimeStampedPVCoordinates"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
