# Autogenerated by devscripts/update-version.py

__version__ = '2024.10.12.232856'

RELEASE_GIT_HEAD = 'babb70960595e2146f06f81affc29c7e713e34e2'

VARIANT = 'pip'

UPDATE_HINT = 'You installed yt-dlp with pip or using the wheel from PyPi; Use that to update'

CHANNEL = 'nightly'

ORIGIN = 'yt-dlp/yt-dlp-nightly-builds'

_pkg_version = '2024.10.12.232856dev'
