# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: com/hayatapps/pa/service/model/paservice.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'com/hayatapps/pa/service/model/paservice.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.com/hayatapps/pa/service/model/paservice.proto\x12\x1e\x63om.hayatapps.ps.service.model\"J\n\tPAService\x12\x12\n\nservice_id\x18\x01 \x01(\r\x12\x15\n\rservice_title\x18\x02 \x01(\t\x12\x12\n\ncreated_at\x18\x03 \x01(\tB+\n\x1e\x63om.hayatapps.ps.service.modelB\x07ServiceP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'com.hayatapps.pa.service.model.paservice_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\036com.hayatapps.ps.service.modelB\007ServiceP\001'
  _globals['_PASERVICE']._serialized_start=82
  _globals['_PASERVICE']._serialized_end=156
# @@protoc_insertion_point(module_scope)
