# Generated File
import typing

import retro_data_structures.properties.corruption.archetypes.ActivationTime as _ActivationTime_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.ActivationTime as _ActivationTime_DKCReturns
import retro_data_structures.properties.prime.archetypes.ActorParameters as _ActorParameters_Prime
import retro_data_structures.properties.echoes.archetypes.ActorParameters as _ActorParameters_Echoes
import retro_data_structures.properties.corruption.archetypes.ActorParameters as _ActorParameters_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.ActorParameters as _ActorParameters_DKCReturns
import retro_data_structures.properties.prime.archetypes.BehaveChance as _BehaveChance_Prime
import retro_data_structures.properties.echoes.archetypes.BehaveChance as _BehaveChance_Echoes
import retro_data_structures.properties.corruption.archetypes.CableProperties as _CableProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CableProperties as _CableProperties_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraConstraints as _CameraConstraints_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraConstraints as _CameraConstraints_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraFieldOfView as _CameraFieldOfView_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraFieldOfView as _CameraFieldOfView_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraInterpolation as _CameraInterpolation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraInterpolation as _CameraInterpolation_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraMotion as _CameraMotion_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraMotion as _CameraMotion_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraNavigation as _CameraNavigation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraNavigation as _CameraNavigation_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraOrientation as _CameraOrientation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraOrientation as _CameraOrientation_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraPosition as _CameraPosition_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraPosition as _CameraPosition_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraRotation as _CameraRotation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraRotation as _CameraRotation_DKCReturns
import retro_data_structures.properties.echoes.archetypes.CameraShakerData as _CameraShakerData_Echoes
import retro_data_structures.properties.corruption.archetypes.CameraShakerData as _CameraShakerData_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraShakerData as _CameraShakerData_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CameraShakerEnvelope as _CameraShakerEnvelope_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CameraShakerEnvelope as _CameraShakerEnvelope_DKCReturns
import retro_data_structures.properties.echoes.archetypes.ConditionalTest as _ConditionalTest_Echoes
import retro_data_structures.properties.corruption.archetypes.ConditionalTest as _ConditionalTest_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.ConditionalTest as _ConditionalTest_DKCReturns
import retro_data_structures.properties.echoes.archetypes.Connection as _Connection_Echoes
import retro_data_structures.properties.corruption.archetypes.Connection as _Connection_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.Connection as _Connection_DKCReturns
import retro_data_structures.properties.corruption.archetypes.ControlCommands as _ControlCommands_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.ControlCommands as _ControlCommands_DKCReturns
import retro_data_structures.properties.corruption.archetypes.Convergence as _Convergence_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.Convergence as _Convergence_DKCReturns
import retro_data_structures.properties.corruption.archetypes.CounterConditions as _CounterConditions_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.CounterConditions as _CounterConditions_DKCReturns
import retro_data_structures.properties.prime.archetypes.DamageInfo as _DamageInfo_Prime
import retro_data_structures.properties.echoes.archetypes.DamageInfo as _DamageInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.DamageInfo as _DamageInfo_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DamageInfo as _DamageInfo_DKCReturns
import retro_data_structures.properties.prime.archetypes.DamageVulnerability as _DamageVulnerability_Prime
import retro_data_structures.properties.echoes.archetypes.DamageVulnerability as _DamageVulnerability_Echoes
import retro_data_structures.properties.corruption.archetypes.DamageVulnerability as _DamageVulnerability_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DamageVulnerability as _DamageVulnerability_DKCReturns
import retro_data_structures.properties.corruption.archetypes.DebrisProperties as _DebrisProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DebrisProperties as _DebrisProperties_DKCReturns
import retro_data_structures.properties.corruption.archetypes.DebrisPropertiesOrientationEnum as _DebrisPropertiesOrientationEnum_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DebrisPropertiesOrientationEnum as _DebrisPropertiesOrientationEnum_DKCReturns
import retro_data_structures.properties.echoes.archetypes.DynamicLightFalloff as _DynamicLightFalloff_Echoes
import retro_data_structures.properties.corruption.archetypes.DynamicLightFalloff as _DynamicLightFalloff_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DynamicLightFalloff as _DynamicLightFalloff_DKCReturns
import retro_data_structures.properties.echoes.archetypes.DynamicLightIntensity as _DynamicLightIntensity_Echoes
import retro_data_structures.properties.corruption.archetypes.DynamicLightIntensity as _DynamicLightIntensity_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DynamicLightIntensity as _DynamicLightIntensity_DKCReturns
import retro_data_structures.properties.echoes.archetypes.DynamicLightMotionSpline as _DynamicLightMotionSpline_Echoes
import retro_data_structures.properties.corruption.archetypes.DynamicLightMotionSpline as _DynamicLightMotionSpline_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DynamicLightMotionSpline as _DynamicLightMotionSpline_DKCReturns
import retro_data_structures.properties.echoes.archetypes.DynamicLightParent as _DynamicLightParent_Echoes
import retro_data_structures.properties.corruption.archetypes.DynamicLightParent as _DynamicLightParent_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DynamicLightParent as _DynamicLightParent_DKCReturns
import retro_data_structures.properties.echoes.archetypes.DynamicLightSpotlight as _DynamicLightSpotlight_Echoes
import retro_data_structures.properties.corruption.archetypes.DynamicLightSpotlight as _DynamicLightSpotlight_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.DynamicLightSpotlight as _DynamicLightSpotlight_DKCReturns
import retro_data_structures.properties.echoes.archetypes.EditorProperties as _EditorProperties_Echoes
import retro_data_structures.properties.corruption.archetypes.EditorProperties as _EditorProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.EditorProperties as _EditorProperties_DKCReturns
import retro_data_structures.properties.corruption.archetypes.FOVInterpolationMethod as _FOVInterpolationMethod_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.FOVInterpolationMethod as _FOVInterpolationMethod_DKCReturns
import retro_data_structures.properties.prime.archetypes.FlareDef as _FlareDef_Prime
import retro_data_structures.properties.echoes.archetypes.FlareDef as _FlareDef_Echoes
import retro_data_structures.properties.corruption.archetypes.FlareDef as _FlareDef_Corruption
import retro_data_structures.properties.corruption.archetypes.GeneratedObjectDeleterProperties as _GeneratedObjectDeleterProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.GeneratedObjectDeleterProperties as _GeneratedObjectDeleterProperties_DKCReturns
import retro_data_structures.properties.prime.archetypes.GrappleParameters as _GrappleParameters_Prime
import retro_data_structures.properties.echoes.archetypes.GrappleParameters as _GrappleParameters_Echoes
import retro_data_structures.properties.echoes.archetypes.GuiWidgetProperties as _GuiWidgetProperties_Echoes
import retro_data_structures.properties.corruption.archetypes.GuiWidgetProperties as _GuiWidgetProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.GuiWidgetProperties as _GuiWidgetProperties_DKCReturns
import retro_data_structures.properties.prime.archetypes.HealthInfo as _HealthInfo_Prime
import retro_data_structures.properties.echoes.archetypes.HealthInfo as _HealthInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.HealthInfo as _HealthInfo_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.HealthInfo as _HealthInfo_DKCReturns
import retro_data_structures.properties.corruption.archetypes.InterpolationMethod as _InterpolationMethod_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.InterpolationMethod as _InterpolationMethod_DKCReturns
import retro_data_structures.properties.echoes.archetypes.LayerInfo as _LayerInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.LayerInfo as _LayerInfo_Corruption
import retro_data_structures.properties.prime.archetypes.LayerSwitch as _LayerSwitch_Prime
import retro_data_structures.properties.echoes.archetypes.LayerSwitch as _LayerSwitch_Echoes
import retro_data_structures.properties.prime.archetypes.LightParameters as _LightParameters_Prime
import retro_data_structures.properties.echoes.archetypes.LightParameters as _LightParameters_Echoes
import retro_data_structures.properties.corruption.archetypes.LightParameters as _LightParameters_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.LightParameters as _LightParameters_DKCReturns
import retro_data_structures.properties.corruption.archetypes.MapControls as _MapControls_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.MapControls as _MapControls_DKCReturns
import retro_data_structures.properties.corruption.archetypes.MiscControls as _MiscControls_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.MiscControls as _MiscControls_DKCReturns
import retro_data_structures.properties.corruption.archetypes.MotionInterpolationMethod as _MotionInterpolationMethod_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.MotionInterpolationMethod as _MotionInterpolationMethod_DKCReturns
import retro_data_structures.properties.corruption.archetypes.MultiModelActorStruct as _MultiModelActorStruct_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.MultiModelActorStruct as _MultiModelActorStruct_DKCReturns
import retro_data_structures.properties.corruption.archetypes.MultiModelInformation as _MultiModelInformation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.MultiModelInformation as _MultiModelInformation_DKCReturns
import retro_data_structures.properties.echoes.archetypes.MysteryFlyerData as _MysteryFlyerData_Echoes
import retro_data_structures.properties.corruption.archetypes.MysteryFlyerData as _MysteryFlyerData_Corruption
import retro_data_structures.properties.corruption.archetypes.NonSlowdown as _NonSlowdown_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.NonSlowdown as _NonSlowdown_DKCReturns
import retro_data_structures.properties.corruption.archetypes.OffsetInterpolant as _OffsetInterpolant_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.OffsetInterpolant as _OffsetInterpolant_DKCReturns
import retro_data_structures.properties.corruption.archetypes.OffsetPosition as _OffsetPosition_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.OffsetPosition as _OffsetPosition_DKCReturns
import retro_data_structures.properties.corruption.archetypes.OffsetSplines as _OffsetSplines_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.OffsetSplines as _OffsetSplines_DKCReturns
import retro_data_structures.properties.corruption.archetypes.OptionalAreaAssetTypes as _OptionalAreaAssetTypes_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.OptionalAreaAssetTypes as _OptionalAreaAssetTypes_DKCReturns
import retro_data_structures.properties.corruption.archetypes.OrientationInterpolationMethod as _OrientationInterpolationMethod_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.OrientationInterpolationMethod as _OrientationInterpolationMethod_DKCReturns
import retro_data_structures.properties.corruption.archetypes.PIDConvergence as _PIDConvergence_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.PIDConvergence as _PIDConvergence_DKCReturns
import retro_data_structures.properties.corruption.archetypes.PathDetermination as _PathDetermination_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.PathDetermination as _PathDetermination_DKCReturns
import retro_data_structures.properties.corruption.archetypes.PathDeterminationMethodType as _PathDeterminationMethodType_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.PathDeterminationMethodType as _PathDeterminationMethodType_DKCReturns
import retro_data_structures.properties.corruption.archetypes.PathPosition as _PathPosition_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.PathPosition as _PathPosition_DKCReturns
import retro_data_structures.properties.prime.archetypes.PatternedAITypedef as _PatternedAITypedef_Prime
import retro_data_structures.properties.echoes.archetypes.PatternedAITypedef as _PatternedAITypedef_Echoes
import retro_data_structures.properties.corruption.archetypes.PatternedAITypedef as _PatternedAITypedef_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.PatternedAITypedef as _PatternedAITypedef_DKCReturns
import retro_data_structures.properties.echoes.archetypes.PlasmaBeamInfo as _PlasmaBeamInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.PlasmaBeamInfo as _PlasmaBeamInfo_Corruption
import retro_data_structures.properties.echoes.archetypes.PlatformMotionProperties as _PlatformMotionProperties_Echoes
import retro_data_structures.properties.corruption.archetypes.PlatformMotionProperties as _PlatformMotionProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.PlatformMotionProperties as _PlatformMotionProperties_DKCReturns
import retro_data_structures.properties.prime.archetypes.PlayerActorStruct as _PlayerActorStruct_Prime
import retro_data_structures.properties.corruption.archetypes.PlayerActorStruct as _PlayerActorStruct_Corruption
import retro_data_structures.properties.corruption.archetypes.ProportionalConvergence as _ProportionalConvergence_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.ProportionalConvergence as _ProportionalConvergence_DKCReturns
import retro_data_structures.properties.corruption.archetypes.RagDollData as _RagDollData_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.RagDollData as _RagDollData_DKCReturns
import retro_data_structures.properties.corruption.archetypes.RevolutionControl as _RevolutionControl_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.RevolutionControl as _RevolutionControl_DKCReturns
import retro_data_structures.properties.corruption.archetypes.RevolutionPhysicalControl as _RevolutionPhysicalControl_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.RevolutionPhysicalControl as _RevolutionPhysicalControl_DKCReturns
import retro_data_structures.properties.echoes.archetypes.RotationSplines as _RotationSplines_Echoes
import retro_data_structures.properties.corruption.archetypes.RotationSplines as _RotationSplines_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.RotationSplines as _RotationSplines_DKCReturns
import retro_data_structures.properties.corruption.archetypes.SavedStateID as _SavedStateID_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SavedStateID as _SavedStateID_DKCReturns
import retro_data_structures.properties.echoes.archetypes.ScaleSplines as _ScaleSplines_Echoes
import retro_data_structures.properties.corruption.archetypes.ScaleSplines as _ScaleSplines_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.ScaleSplines as _ScaleSplines_DKCReturns
import retro_data_structures.properties.echoes.archetypes.ScanInfoSecondaryModel as _ScanInfoSecondaryModel_Echoes
import retro_data_structures.properties.corruption.archetypes.ScanInfoSecondaryModel as _ScanInfoSecondaryModel_Corruption
import retro_data_structures.properties.prime.archetypes.ScannableParameters as _ScannableParameters_Prime
import retro_data_structures.properties.echoes.archetypes.ScannableParameters as _ScannableParameters_Echoes
import retro_data_structures.properties.corruption.archetypes.ScannableParameters as _ScannableParameters_Corruption
import retro_data_structures.properties.echoes.archetypes.ShockWaveInfo as _ShockWaveInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.ShockWaveInfo as _ShockWaveInfo_Corruption
import retro_data_structures.properties.echoes.archetypes.SpacePirateWeaponData as _SpacePirateWeaponData_Echoes
import retro_data_structures.properties.corruption.archetypes.SpacePirateWeaponData as _SpacePirateWeaponData_Corruption
import retro_data_structures.properties.prime.archetypes.SpindleCameraStruct as _SpindleCameraStruct_Prime
import retro_data_structures.properties.echoes.archetypes.SpindleCameraStruct as _SpindleCameraStruct_Echoes
import retro_data_structures.properties.corruption.archetypes.SpindleOrientation as _SpindleOrientation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SpindleOrientation as _SpindleOrientation_DKCReturns
import retro_data_structures.properties.corruption.archetypes.SpindlePosition as _SpindlePosition_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SpindlePosition as _SpindlePosition_DKCReturns
import retro_data_structures.properties.corruption.archetypes.SpindlePositionInterpolant as _SpindlePositionInterpolant_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SpindlePositionInterpolant as _SpindlePositionInterpolant_DKCReturns
import retro_data_structures.properties.echoes.archetypes.SplineType as _SplineType_Echoes
import retro_data_structures.properties.corruption.archetypes.SplineType as _SplineType_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SplineType as _SplineType_DKCReturns
import retro_data_structures.properties.corruption.archetypes.SpringConvergence as _SpringConvergence_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SpringConvergence as _SpringConvergence_DKCReturns
import retro_data_structures.properties.corruption.archetypes.SurfaceOrientation as _SurfaceOrientation_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SurfaceOrientation as _SurfaceOrientation_DKCReturns
import retro_data_structures.properties.corruption.archetypes.SurfacePosition as _SurfacePosition_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SurfacePosition as _SurfacePosition_DKCReturns
import retro_data_structures.properties.echoes.archetypes.SurroundPan as _SurroundPan_Echoes
import retro_data_structures.properties.corruption.archetypes.SurroundPan as _SurroundPan_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.SurroundPan as _SurroundPan_DKCReturns
import retro_data_structures.properties.echoes.archetypes.TBallTransitionResources as _TBallTransitionResources_Echoes
import retro_data_structures.properties.corruption.archetypes.TBallTransitionResources as _TBallTransitionResources_Corruption
import retro_data_structures.properties.echoes.archetypes.TBeamInfo as _TBeamInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.TBeamInfo as _TBeamInfo_Corruption
import retro_data_structures.properties.echoes.archetypes.TDamageInfo as _TDamageInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.TDamageInfo as _TDamageInfo_Corruption
import retro_data_structures.properties.echoes.archetypes.TGunResources as _TGunResources_Echoes
import retro_data_structures.properties.corruption.archetypes.TGunResources as _TGunResources_Corruption
import retro_data_structures.properties.echoes.archetypes.TIcon.Configurations as _TIcon_Configurations_Echoes
import retro_data_structures.properties.corruption.archetypes.TIcon.Configurations as _TIcon_Configurations_Corruption
import retro_data_structures.properties.echoes.archetypes.TWeaponDamage as _TWeaponDamage_Echoes
import retro_data_structures.properties.corruption.archetypes.TWeaponDamage as _TWeaponDamage_Corruption
import retro_data_structures.properties.echoes.archetypes.TextProperties as _TextProperties_Echoes
import retro_data_structures.properties.corruption.archetypes.TextProperties as _TextProperties_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.TextProperties as _TextProperties_DKCReturns
import retro_data_structures.properties.echoes.archetypes.Transform as _Transform_Echoes
import retro_data_structures.properties.corruption.archetypes.Transform as _Transform_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.Transform as _Transform_DKCReturns
import retro_data_structures.properties.corruption.archetypes.TranslationSplines as _TranslationSplines_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.TranslationSplines as _TranslationSplines_DKCReturns
import retro_data_structures.properties.echoes.archetypes.TriggerInfo as _TriggerInfo_Echoes
import retro_data_structures.properties.corruption.archetypes.TriggerInfo as _TriggerInfo_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.TriggerInfo as _TriggerInfo_DKCReturns
import retro_data_structures.properties.echoes.archetypes.TweakAutoMapper.Base as _TweakAutoMapper_Base_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakAutoMapper.Base as _TweakAutoMapper_Base_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakAutoMapper.DoorColors as _TweakAutoMapper_DoorColors_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakAutoMapper.DoorColors as _TweakAutoMapper_DoorColors_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.BoostBall as _TweakBall_BoostBall_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.BoostBall as _TweakBall_BoostBall_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.Camera as _TweakBall_Camera_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.Camera as _TweakBall_Camera_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.CannonBall as _TweakBall_CannonBall_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.CannonBall as _TweakBall_CannonBall_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.DeathBall as _TweakBall_DeathBall_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.DeathBall as _TweakBall_DeathBall_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.Misc as _TweakBall_Misc_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.Misc as _TweakBall_Misc_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.Movement as _TweakBall_Movement_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.Movement as _TweakBall_Movement_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakBall.ScrewAttack as _TweakBall_ScrewAttack_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakBall.ScrewAttack as _TweakBall_ScrewAttack_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGuiColors.HUDColorsTypedef as _TweakGuiColors_HUDColorsTypedef_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGuiColors.HUDColorsTypedef as _TweakGuiColors_HUDColorsTypedef_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGuiColors.Misc as _TweakGuiColors_Misc_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGuiColors.Misc as _TweakGuiColors_Misc_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGuiColors.Multiplayer as _TweakGuiColors_Multiplayer_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGuiColors.Multiplayer as _TweakGuiColors_Multiplayer_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGuiColors.TurretHudTypedef as _TweakGuiColors_TurretHudTypedef_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGuiColors.TurretHudTypedef as _TweakGuiColors_TurretHudTypedef_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.Completion as _TweakGui_Completion_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.Completion as _TweakGui_Completion_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.Credits as _TweakGui_Credits_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.Credits as _TweakGui_Credits_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.HudColorTypedef as _TweakGui_HudColorTypedef_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.HudColorTypedef as _TweakGui_HudColorTypedef_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.Misc as _TweakGui_Misc_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.Misc as _TweakGui_Misc_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.MovieVolumes as _TweakGui_MovieVolumes_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.MovieVolumes as _TweakGui_MovieVolumes_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.ScanVisor as _TweakGui_ScanVisor_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.ScanVisor as _TweakGui_ScanVisor_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.ScannableObjectDownloadTimes as _TweakGui_ScannableObjectDownloadTimes_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.ScannableObjectDownloadTimes as _TweakGui_ScannableObjectDownloadTimes_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakGui.VisorColorSchemeTypedef as _TweakGui_VisorColorSchemeTypedef_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakGui.VisorColorSchemeTypedef as _TweakGui_VisorColorSchemeTypedef_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.Arm.Position as _TweakPlayerGun_Arm_Position_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.Arm.Position as _TweakPlayerGun_Arm_Position_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.Beam.Misc as _TweakPlayerGun_Beam_Misc_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.Beam.Misc as _TweakPlayerGun_Beam_Misc_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.Holstering as _TweakPlayerGun_Holstering_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.Holstering as _TweakPlayerGun_Holstering_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.Misc as _TweakPlayerGun_Misc_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.Misc as _TweakPlayerGun_Misc_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.Position as _TweakPlayerGun_Position_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.Position as _TweakPlayerGun_Position_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.RicochetDamage.Factor as _TweakPlayerGun_RicochetDamage_Factor_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.RicochetDamage.Factor as _TweakPlayerGun_RicochetDamage_Factor_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerGun.Weapons as _TweakPlayerGun_Weapons_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerGun.Weapons as _TweakPlayerGun_Weapons_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerRes.AutoMapperIcons as _TweakPlayerRes_AutoMapperIcons_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerRes.AutoMapperIcons as _TweakPlayerRes_AutoMapperIcons_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayerRes.MapScreenIcons as _TweakPlayerRes_MapScreenIcons_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayerRes.MapScreenIcons as _TweakPlayerRes_MapScreenIcons_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.AimStuff as _TweakPlayer_AimStuff_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.AimStuff as _TweakPlayer_AimStuff_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Collision as _TweakPlayer_Collision_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Collision as _TweakPlayer_Collision_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.FirstPersonCamera as _TweakPlayer_FirstPersonCamera_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.FirstPersonCamera as _TweakPlayer_FirstPersonCamera_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Frozen as _TweakPlayer_Frozen_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Frozen as _TweakPlayer_Frozen_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Grapple as _TweakPlayer_Grapple_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Grapple as _TweakPlayer_Grapple_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.GrappleBeam as _TweakPlayer_GrappleBeam_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.GrappleBeam as _TweakPlayer_GrappleBeam_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Misc as _TweakPlayer_Misc_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Misc as _TweakPlayer_Misc_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Motion as _TweakPlayer_Motion_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Motion as _TweakPlayer_Motion_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Orbit as _TweakPlayer_Orbit_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Orbit as _TweakPlayer_Orbit_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.ScanVisor as _TweakPlayer_ScanVisor_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.ScanVisor as _TweakPlayer_ScanVisor_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.Shield as _TweakPlayer_Shield_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.Shield as _TweakPlayer_Shield_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakPlayer.SuitDamageReduction as _TweakPlayer_SuitDamageReduction_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakPlayer.SuitDamageReduction as _TweakPlayer_SuitDamageReduction_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakTargeting.Charge.Gauge as _TweakTargeting_Charge_Gauge_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakTargeting.Charge.Gauge as _TweakTargeting_Charge_Gauge_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakTargeting.LockDagger as _TweakTargeting_LockDagger_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakTargeting.LockDagger as _TweakTargeting_LockDagger_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakTargeting.LockFire as _TweakTargeting_LockFire_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakTargeting.LockFire as _TweakTargeting_LockFire_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakTargeting.OuterBeamIcon as _TweakTargeting_OuterBeamIcon_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakTargeting.OuterBeamIcon as _TweakTargeting_OuterBeamIcon_Corruption
import retro_data_structures.properties.echoes.archetypes.TweakTargeting.Scan as _TweakTargeting_Scan_Echoes
import retro_data_structures.properties.corruption.archetypes.TweakTargeting.Scan as _TweakTargeting_Scan_Corruption
import retro_data_structures.properties.prime.archetypes.Vector2f as _Vector2f_Prime
import retro_data_structures.properties.echoes.archetypes.Vector2f as _Vector2f_Echoes
import retro_data_structures.properties.corruption.archetypes.Vector2f as _Vector2f_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.Vector2f as _Vector2f_DKCReturns
import retro_data_structures.properties.corruption.archetypes.VelocityConvergence as _VelocityConvergence_Corruption
import retro_data_structures.properties.dkc_returns.archetypes.VelocityConvergence as _VelocityConvergence_DKCReturns
import retro_data_structures.properties.prime.archetypes.VisorParameters as _VisorParameters_Prime
import retro_data_structures.properties.echoes.archetypes.VisorParameters as _VisorParameters_Echoes
import retro_data_structures.properties.corruption.archetypes.VisorParameters as _VisorParameters_Corruption
import retro_data_structures.properties.echoes.archetypes.WeaponVulnerability as _WeaponVulnerability_Echoes
import retro_data_structures.properties.corruption.archetypes.WeaponVulnerability as _WeaponVulnerability_Corruption

ActivationTime = typing.Union[
    _ActivationTime_Corruption.ActivationTime,
    _ActivationTime_DKCReturns.ActivationTime
]
ActorParameters = typing.Union[
    _ActorParameters_Prime.ActorParameters,
    _ActorParameters_Echoes.ActorParameters,
    _ActorParameters_Corruption.ActorParameters,
    _ActorParameters_DKCReturns.ActorParameters
]
BehaveChance = typing.Union[
    _BehaveChance_Prime.BehaveChance,
    _BehaveChance_Echoes.BehaveChance
]
CableProperties = typing.Union[
    _CableProperties_Corruption.CableProperties,
    _CableProperties_DKCReturns.CableProperties
]
CameraConstraints = typing.Union[
    _CameraConstraints_Corruption.CameraConstraints,
    _CameraConstraints_DKCReturns.CameraConstraints
]
CameraFieldOfView = typing.Union[
    _CameraFieldOfView_Corruption.CameraFieldOfView,
    _CameraFieldOfView_DKCReturns.CameraFieldOfView
]
CameraInterpolation = typing.Union[
    _CameraInterpolation_Corruption.CameraInterpolation,
    _CameraInterpolation_DKCReturns.CameraInterpolation
]
CameraMotion = typing.Union[
    _CameraMotion_Corruption.CameraMotion,
    _CameraMotion_DKCReturns.CameraMotion
]
CameraNavigation = typing.Union[
    _CameraNavigation_Corruption.CameraNavigation,
    _CameraNavigation_DKCReturns.CameraNavigation
]
CameraOrientation = typing.Union[
    _CameraOrientation_Corruption.CameraOrientation,
    _CameraOrientation_DKCReturns.CameraOrientation
]
CameraPosition = typing.Union[
    _CameraPosition_Corruption.CameraPosition,
    _CameraPosition_DKCReturns.CameraPosition
]
CameraRotation = typing.Union[
    _CameraRotation_Corruption.CameraRotation,
    _CameraRotation_DKCReturns.CameraRotation
]
CameraShakerData = typing.Union[
    _CameraShakerData_Echoes.CameraShakerData,
    _CameraShakerData_Corruption.CameraShakerData,
    _CameraShakerData_DKCReturns.CameraShakerData
]
CameraShakerEnvelope = typing.Union[
    _CameraShakerEnvelope_Corruption.CameraShakerEnvelope,
    _CameraShakerEnvelope_DKCReturns.CameraShakerEnvelope
]
ConditionalTest = typing.Union[
    _ConditionalTest_Echoes.ConditionalTest,
    _ConditionalTest_Corruption.ConditionalTest,
    _ConditionalTest_DKCReturns.ConditionalTest
]
Connection = typing.Union[
    _Connection_Echoes.Connection,
    _Connection_Corruption.Connection,
    _Connection_DKCReturns.Connection
]
ControlCommands = typing.Union[
    _ControlCommands_Corruption.ControlCommands,
    _ControlCommands_DKCReturns.ControlCommands
]
Convergence = typing.Union[
    _Convergence_Corruption.Convergence,
    _Convergence_DKCReturns.Convergence
]
CounterConditions = typing.Union[
    _CounterConditions_Corruption.CounterConditions,
    _CounterConditions_DKCReturns.CounterConditions
]
DamageInfo = typing.Union[
    _DamageInfo_Prime.DamageInfo,
    _DamageInfo_Echoes.DamageInfo,
    _DamageInfo_Corruption.DamageInfo,
    _DamageInfo_DKCReturns.DamageInfo
]
DamageVulnerability = typing.Union[
    _DamageVulnerability_Prime.DamageVulnerability,
    _DamageVulnerability_Echoes.DamageVulnerability,
    _DamageVulnerability_Corruption.DamageVulnerability,
    _DamageVulnerability_DKCReturns.DamageVulnerability
]
DebrisProperties = typing.Union[
    _DebrisProperties_Corruption.DebrisProperties,
    _DebrisProperties_DKCReturns.DebrisProperties
]
DebrisPropertiesOrientationEnum = typing.Union[
    _DebrisPropertiesOrientationEnum_Corruption.DebrisPropertiesOrientationEnum,
    _DebrisPropertiesOrientationEnum_DKCReturns.DebrisPropertiesOrientationEnum
]
DynamicLightFalloff = typing.Union[
    _DynamicLightFalloff_Echoes.DynamicLightFalloff,
    _DynamicLightFalloff_Corruption.DynamicLightFalloff,
    _DynamicLightFalloff_DKCReturns.DynamicLightFalloff
]
DynamicLightIntensity = typing.Union[
    _DynamicLightIntensity_Echoes.DynamicLightIntensity,
    _DynamicLightIntensity_Corruption.DynamicLightIntensity,
    _DynamicLightIntensity_DKCReturns.DynamicLightIntensity
]
DynamicLightMotionSpline = typing.Union[
    _DynamicLightMotionSpline_Echoes.DynamicLightMotionSpline,
    _DynamicLightMotionSpline_Corruption.DynamicLightMotionSpline,
    _DynamicLightMotionSpline_DKCReturns.DynamicLightMotionSpline
]
DynamicLightParent = typing.Union[
    _DynamicLightParent_Echoes.DynamicLightParent,
    _DynamicLightParent_Corruption.DynamicLightParent,
    _DynamicLightParent_DKCReturns.DynamicLightParent
]
DynamicLightSpotlight = typing.Union[
    _DynamicLightSpotlight_Echoes.DynamicLightSpotlight,
    _DynamicLightSpotlight_Corruption.DynamicLightSpotlight,
    _DynamicLightSpotlight_DKCReturns.DynamicLightSpotlight
]
EditorProperties = typing.Union[
    _EditorProperties_Echoes.EditorProperties,
    _EditorProperties_Corruption.EditorProperties,
    _EditorProperties_DKCReturns.EditorProperties
]
FOVInterpolationMethod = typing.Union[
    _FOVInterpolationMethod_Corruption.FOVInterpolationMethod,
    _FOVInterpolationMethod_DKCReturns.FOVInterpolationMethod
]
FlareDef = typing.Union[
    _FlareDef_Prime.FlareDef,
    _FlareDef_Echoes.FlareDef,
    _FlareDef_Corruption.FlareDef
]
GeneratedObjectDeleterProperties = typing.Union[
    _GeneratedObjectDeleterProperties_Corruption.GeneratedObjectDeleterProperties,
    _GeneratedObjectDeleterProperties_DKCReturns.GeneratedObjectDeleterProperties
]
GrappleParameters = typing.Union[
    _GrappleParameters_Prime.GrappleParameters,
    _GrappleParameters_Echoes.GrappleParameters
]
GuiWidgetProperties = typing.Union[
    _GuiWidgetProperties_Echoes.GuiWidgetProperties,
    _GuiWidgetProperties_Corruption.GuiWidgetProperties,
    _GuiWidgetProperties_DKCReturns.GuiWidgetProperties
]
HealthInfo = typing.Union[
    _HealthInfo_Prime.HealthInfo,
    _HealthInfo_Echoes.HealthInfo,
    _HealthInfo_Corruption.HealthInfo,
    _HealthInfo_DKCReturns.HealthInfo
]
InterpolationMethod = typing.Union[
    _InterpolationMethod_Corruption.InterpolationMethod,
    _InterpolationMethod_DKCReturns.InterpolationMethod
]
LayerInfo = typing.Union[
    _LayerInfo_Echoes.LayerInfo,
    _LayerInfo_Corruption.LayerInfo
]
LayerSwitch = typing.Union[
    _LayerSwitch_Prime.LayerSwitch,
    _LayerSwitch_Echoes.LayerSwitch
]
LightParameters = typing.Union[
    _LightParameters_Prime.LightParameters,
    _LightParameters_Echoes.LightParameters,
    _LightParameters_Corruption.LightParameters,
    _LightParameters_DKCReturns.LightParameters
]
MapControls = typing.Union[
    _MapControls_Corruption.MapControls,
    _MapControls_DKCReturns.MapControls
]
MiscControls = typing.Union[
    _MiscControls_Corruption.MiscControls,
    _MiscControls_DKCReturns.MiscControls
]
MotionInterpolationMethod = typing.Union[
    _MotionInterpolationMethod_Corruption.MotionInterpolationMethod,
    _MotionInterpolationMethod_DKCReturns.MotionInterpolationMethod
]
MultiModelActorStruct = typing.Union[
    _MultiModelActorStruct_Corruption.MultiModelActorStruct,
    _MultiModelActorStruct_DKCReturns.MultiModelActorStruct
]
MultiModelInformation = typing.Union[
    _MultiModelInformation_Corruption.MultiModelInformation,
    _MultiModelInformation_DKCReturns.MultiModelInformation
]
MysteryFlyerData = typing.Union[
    _MysteryFlyerData_Echoes.MysteryFlyerData,
    _MysteryFlyerData_Corruption.MysteryFlyerData
]
NonSlowdown = typing.Union[
    _NonSlowdown_Corruption.NonSlowdown,
    _NonSlowdown_DKCReturns.NonSlowdown
]
OffsetInterpolant = typing.Union[
    _OffsetInterpolant_Corruption.OffsetInterpolant,
    _OffsetInterpolant_DKCReturns.OffsetInterpolant
]
OffsetPosition = typing.Union[
    _OffsetPosition_Corruption.OffsetPosition,
    _OffsetPosition_DKCReturns.OffsetPosition
]
OffsetSplines = typing.Union[
    _OffsetSplines_Corruption.OffsetSplines,
    _OffsetSplines_DKCReturns.OffsetSplines
]
OptionalAreaAssetTypes = typing.Union[
    _OptionalAreaAssetTypes_Corruption.OptionalAreaAssetTypes,
    _OptionalAreaAssetTypes_DKCReturns.OptionalAreaAssetTypes
]
OrientationInterpolationMethod = typing.Union[
    _OrientationInterpolationMethod_Corruption.OrientationInterpolationMethod,
    _OrientationInterpolationMethod_DKCReturns.OrientationInterpolationMethod
]
PIDConvergence = typing.Union[
    _PIDConvergence_Corruption.PIDConvergence,
    _PIDConvergence_DKCReturns.PIDConvergence
]
PathDetermination = typing.Union[
    _PathDetermination_Corruption.PathDetermination,
    _PathDetermination_DKCReturns.PathDetermination
]
PathDeterminationMethodType = typing.Union[
    _PathDeterminationMethodType_Corruption.PathDeterminationMethodType,
    _PathDeterminationMethodType_DKCReturns.PathDeterminationMethodType
]
PathPosition = typing.Union[
    _PathPosition_Corruption.PathPosition,
    _PathPosition_DKCReturns.PathPosition
]
PatternedAITypedef = typing.Union[
    _PatternedAITypedef_Prime.PatternedAITypedef,
    _PatternedAITypedef_Echoes.PatternedAITypedef,
    _PatternedAITypedef_Corruption.PatternedAITypedef,
    _PatternedAITypedef_DKCReturns.PatternedAITypedef
]
PlasmaBeamInfo = typing.Union[
    _PlasmaBeamInfo_Echoes.PlasmaBeamInfo,
    _PlasmaBeamInfo_Corruption.PlasmaBeamInfo
]
PlatformMotionProperties = typing.Union[
    _PlatformMotionProperties_Echoes.PlatformMotionProperties,
    _PlatformMotionProperties_Corruption.PlatformMotionProperties,
    _PlatformMotionProperties_DKCReturns.PlatformMotionProperties
]
PlayerActorStruct = typing.Union[
    _PlayerActorStruct_Prime.PlayerActorStruct,
    _PlayerActorStruct_Corruption.PlayerActorStruct
]
ProportionalConvergence = typing.Union[
    _ProportionalConvergence_Corruption.ProportionalConvergence,
    _ProportionalConvergence_DKCReturns.ProportionalConvergence
]
RagDollData = typing.Union[
    _RagDollData_Corruption.RagDollData,
    _RagDollData_DKCReturns.RagDollData
]
RevolutionControl = typing.Union[
    _RevolutionControl_Corruption.RevolutionControl,
    _RevolutionControl_DKCReturns.RevolutionControl
]
RevolutionPhysicalControl = typing.Union[
    _RevolutionPhysicalControl_Corruption.RevolutionPhysicalControl,
    _RevolutionPhysicalControl_DKCReturns.RevolutionPhysicalControl
]
RotationSplines = typing.Union[
    _RotationSplines_Echoes.RotationSplines,
    _RotationSplines_Corruption.RotationSplines,
    _RotationSplines_DKCReturns.RotationSplines
]
SavedStateID = typing.Union[
    _SavedStateID_Corruption.SavedStateID,
    _SavedStateID_DKCReturns.SavedStateID
]
ScaleSplines = typing.Union[
    _ScaleSplines_Echoes.ScaleSplines,
    _ScaleSplines_Corruption.ScaleSplines,
    _ScaleSplines_DKCReturns.ScaleSplines
]
ScanInfoSecondaryModel = typing.Union[
    _ScanInfoSecondaryModel_Echoes.ScanInfoSecondaryModel,
    _ScanInfoSecondaryModel_Corruption.ScanInfoSecondaryModel
]
ScannableParameters = typing.Union[
    _ScannableParameters_Prime.ScannableParameters,
    _ScannableParameters_Echoes.ScannableParameters,
    _ScannableParameters_Corruption.ScannableParameters
]
ShockWaveInfo = typing.Union[
    _ShockWaveInfo_Echoes.ShockWaveInfo,
    _ShockWaveInfo_Corruption.ShockWaveInfo
]
SpacePirateWeaponData = typing.Union[
    _SpacePirateWeaponData_Echoes.SpacePirateWeaponData,
    _SpacePirateWeaponData_Corruption.SpacePirateWeaponData
]
SpindleCameraStruct = typing.Union[
    _SpindleCameraStruct_Prime.SpindleCameraStruct,
    _SpindleCameraStruct_Echoes.SpindleCameraStruct
]
SpindleOrientation = typing.Union[
    _SpindleOrientation_Corruption.SpindleOrientation,
    _SpindleOrientation_DKCReturns.SpindleOrientation
]
SpindlePosition = typing.Union[
    _SpindlePosition_Corruption.SpindlePosition,
    _SpindlePosition_DKCReturns.SpindlePosition
]
SpindlePositionInterpolant = typing.Union[
    _SpindlePositionInterpolant_Corruption.SpindlePositionInterpolant,
    _SpindlePositionInterpolant_DKCReturns.SpindlePositionInterpolant
]
SplineType = typing.Union[
    _SplineType_Echoes.SplineType,
    _SplineType_Corruption.SplineType,
    _SplineType_DKCReturns.SplineType
]
SpringConvergence = typing.Union[
    _SpringConvergence_Corruption.SpringConvergence,
    _SpringConvergence_DKCReturns.SpringConvergence
]
SurfaceOrientation = typing.Union[
    _SurfaceOrientation_Corruption.SurfaceOrientation,
    _SurfaceOrientation_DKCReturns.SurfaceOrientation
]
SurfacePosition = typing.Union[
    _SurfacePosition_Corruption.SurfacePosition,
    _SurfacePosition_DKCReturns.SurfacePosition
]
SurroundPan = typing.Union[
    _SurroundPan_Echoes.SurroundPan,
    _SurroundPan_Corruption.SurroundPan,
    _SurroundPan_DKCReturns.SurroundPan
]
TBallTransitionResources = typing.Union[
    _TBallTransitionResources_Echoes.TBallTransitionResources,
    _TBallTransitionResources_Corruption.TBallTransitionResources
]
TBeamInfo = typing.Union[
    _TBeamInfo_Echoes.TBeamInfo,
    _TBeamInfo_Corruption.TBeamInfo
]
TDamageInfo = typing.Union[
    _TDamageInfo_Echoes.TDamageInfo,
    _TDamageInfo_Corruption.TDamageInfo
]
TGunResources = typing.Union[
    _TGunResources_Echoes.TGunResources,
    _TGunResources_Corruption.TGunResources
]
TIcon_Configurations = typing.Union[
    _TIcon_Configurations_Echoes.Configurations,
    _TIcon_Configurations_Corruption.Configurations
]
TWeaponDamage = typing.Union[
    _TWeaponDamage_Echoes.TWeaponDamage,
    _TWeaponDamage_Corruption.TWeaponDamage
]
TextProperties = typing.Union[
    _TextProperties_Echoes.TextProperties,
    _TextProperties_Corruption.TextProperties,
    _TextProperties_DKCReturns.TextProperties
]
Transform = typing.Union[
    _Transform_Echoes.Transform,
    _Transform_Corruption.Transform,
    _Transform_DKCReturns.Transform
]
TranslationSplines = typing.Union[
    _TranslationSplines_Corruption.TranslationSplines,
    _TranslationSplines_DKCReturns.TranslationSplines
]
TriggerInfo = typing.Union[
    _TriggerInfo_Echoes.TriggerInfo,
    _TriggerInfo_Corruption.TriggerInfo,
    _TriggerInfo_DKCReturns.TriggerInfo
]
TweakAutoMapper_Base = typing.Union[
    _TweakAutoMapper_Base_Echoes.Base,
    _TweakAutoMapper_Base_Corruption.Base
]
TweakAutoMapper_DoorColors = typing.Union[
    _TweakAutoMapper_DoorColors_Echoes.DoorColors,
    _TweakAutoMapper_DoorColors_Corruption.DoorColors
]
TweakBall_BoostBall = typing.Union[
    _TweakBall_BoostBall_Echoes.BoostBall,
    _TweakBall_BoostBall_Corruption.BoostBall
]
TweakBall_Camera = typing.Union[
    _TweakBall_Camera_Echoes.Camera,
    _TweakBall_Camera_Corruption.Camera
]
TweakBall_CannonBall = typing.Union[
    _TweakBall_CannonBall_Echoes.CannonBall,
    _TweakBall_CannonBall_Corruption.CannonBall
]
TweakBall_DeathBall = typing.Union[
    _TweakBall_DeathBall_Echoes.DeathBall,
    _TweakBall_DeathBall_Corruption.DeathBall
]
TweakBall_Misc = typing.Union[
    _TweakBall_Misc_Echoes.Misc,
    _TweakBall_Misc_Corruption.Misc
]
TweakBall_Movement = typing.Union[
    _TweakBall_Movement_Echoes.Movement,
    _TweakBall_Movement_Corruption.Movement
]
TweakBall_ScrewAttack = typing.Union[
    _TweakBall_ScrewAttack_Echoes.ScrewAttack,
    _TweakBall_ScrewAttack_Corruption.ScrewAttack
]
TweakGuiColors_HUDColorsTypedef = typing.Union[
    _TweakGuiColors_HUDColorsTypedef_Echoes.HUDColorsTypedef,
    _TweakGuiColors_HUDColorsTypedef_Corruption.HUDColorsTypedef
]
TweakGuiColors_Misc = typing.Union[
    _TweakGuiColors_Misc_Echoes.Misc,
    _TweakGuiColors_Misc_Corruption.Misc
]
TweakGuiColors_Multiplayer = typing.Union[
    _TweakGuiColors_Multiplayer_Echoes.Multiplayer,
    _TweakGuiColors_Multiplayer_Corruption.Multiplayer
]
TweakGuiColors_TurretHudTypedef = typing.Union[
    _TweakGuiColors_TurretHudTypedef_Echoes.TurretHudTypedef,
    _TweakGuiColors_TurretHudTypedef_Corruption.TurretHudTypedef
]
TweakGui_Completion = typing.Union[
    _TweakGui_Completion_Echoes.Completion,
    _TweakGui_Completion_Corruption.Completion
]
TweakGui_Credits = typing.Union[
    _TweakGui_Credits_Echoes.Credits,
    _TweakGui_Credits_Corruption.Credits
]
TweakGui_HudColorTypedef = typing.Union[
    _TweakGui_HudColorTypedef_Echoes.HudColorTypedef,
    _TweakGui_HudColorTypedef_Corruption.HudColorTypedef
]
TweakGui_Misc = typing.Union[
    _TweakGui_Misc_Echoes.Misc,
    _TweakGui_Misc_Corruption.Misc
]
TweakGui_MovieVolumes = typing.Union[
    _TweakGui_MovieVolumes_Echoes.MovieVolumes,
    _TweakGui_MovieVolumes_Corruption.MovieVolumes
]
TweakGui_ScanVisor = typing.Union[
    _TweakGui_ScanVisor_Echoes.ScanVisor,
    _TweakGui_ScanVisor_Corruption.ScanVisor
]
TweakGui_ScannableObjectDownloadTimes = typing.Union[
    _TweakGui_ScannableObjectDownloadTimes_Echoes.ScannableObjectDownloadTimes,
    _TweakGui_ScannableObjectDownloadTimes_Corruption.ScannableObjectDownloadTimes
]
TweakGui_VisorColorSchemeTypedef = typing.Union[
    _TweakGui_VisorColorSchemeTypedef_Echoes.VisorColorSchemeTypedef,
    _TweakGui_VisorColorSchemeTypedef_Corruption.VisorColorSchemeTypedef
]
TweakPlayerGun_Arm_Position = typing.Union[
    _TweakPlayerGun_Arm_Position_Echoes.Position,
    _TweakPlayerGun_Arm_Position_Corruption.Position
]
TweakPlayerGun_Beam_Misc = typing.Union[
    _TweakPlayerGun_Beam_Misc_Echoes.Misc,
    _TweakPlayerGun_Beam_Misc_Corruption.Misc
]
TweakPlayerGun_Holstering = typing.Union[
    _TweakPlayerGun_Holstering_Echoes.Holstering,
    _TweakPlayerGun_Holstering_Corruption.Holstering
]
TweakPlayerGun_Misc = typing.Union[
    _TweakPlayerGun_Misc_Echoes.Misc,
    _TweakPlayerGun_Misc_Corruption.Misc
]
TweakPlayerGun_Position = typing.Union[
    _TweakPlayerGun_Position_Echoes.Position,
    _TweakPlayerGun_Position_Corruption.Position
]
TweakPlayerGun_RicochetDamage_Factor = typing.Union[
    _TweakPlayerGun_RicochetDamage_Factor_Echoes.Factor,
    _TweakPlayerGun_RicochetDamage_Factor_Corruption.Factor
]
TweakPlayerGun_Weapons = typing.Union[
    _TweakPlayerGun_Weapons_Echoes.Weapons,
    _TweakPlayerGun_Weapons_Corruption.Weapons
]
TweakPlayerRes_AutoMapperIcons = typing.Union[
    _TweakPlayerRes_AutoMapperIcons_Echoes.AutoMapperIcons,
    _TweakPlayerRes_AutoMapperIcons_Corruption.AutoMapperIcons
]
TweakPlayerRes_MapScreenIcons = typing.Union[
    _TweakPlayerRes_MapScreenIcons_Echoes.MapScreenIcons,
    _TweakPlayerRes_MapScreenIcons_Corruption.MapScreenIcons
]
TweakPlayer_AimStuff = typing.Union[
    _TweakPlayer_AimStuff_Echoes.AimStuff,
    _TweakPlayer_AimStuff_Corruption.AimStuff
]
TweakPlayer_Collision = typing.Union[
    _TweakPlayer_Collision_Echoes.Collision,
    _TweakPlayer_Collision_Corruption.Collision
]
TweakPlayer_FirstPersonCamera = typing.Union[
    _TweakPlayer_FirstPersonCamera_Echoes.FirstPersonCamera,
    _TweakPlayer_FirstPersonCamera_Corruption.FirstPersonCamera
]
TweakPlayer_Frozen = typing.Union[
    _TweakPlayer_Frozen_Echoes.Frozen,
    _TweakPlayer_Frozen_Corruption.Frozen
]
TweakPlayer_Grapple = typing.Union[
    _TweakPlayer_Grapple_Echoes.Grapple,
    _TweakPlayer_Grapple_Corruption.Grapple
]
TweakPlayer_GrappleBeam = typing.Union[
    _TweakPlayer_GrappleBeam_Echoes.GrappleBeam,
    _TweakPlayer_GrappleBeam_Corruption.GrappleBeam
]
TweakPlayer_Misc = typing.Union[
    _TweakPlayer_Misc_Echoes.Misc,
    _TweakPlayer_Misc_Corruption.Misc
]
TweakPlayer_Motion = typing.Union[
    _TweakPlayer_Motion_Echoes.Motion,
    _TweakPlayer_Motion_Corruption.Motion
]
TweakPlayer_Orbit = typing.Union[
    _TweakPlayer_Orbit_Echoes.Orbit,
    _TweakPlayer_Orbit_Corruption.Orbit
]
TweakPlayer_ScanVisor = typing.Union[
    _TweakPlayer_ScanVisor_Echoes.ScanVisor,
    _TweakPlayer_ScanVisor_Corruption.ScanVisor
]
TweakPlayer_Shield = typing.Union[
    _TweakPlayer_Shield_Echoes.Shield,
    _TweakPlayer_Shield_Corruption.Shield
]
TweakPlayer_SuitDamageReduction = typing.Union[
    _TweakPlayer_SuitDamageReduction_Echoes.SuitDamageReduction,
    _TweakPlayer_SuitDamageReduction_Corruption.SuitDamageReduction
]
TweakTargeting_Charge_Gauge = typing.Union[
    _TweakTargeting_Charge_Gauge_Echoes.Gauge,
    _TweakTargeting_Charge_Gauge_Corruption.Gauge
]
TweakTargeting_LockDagger = typing.Union[
    _TweakTargeting_LockDagger_Echoes.LockDagger,
    _TweakTargeting_LockDagger_Corruption.LockDagger
]
TweakTargeting_LockFire = typing.Union[
    _TweakTargeting_LockFire_Echoes.LockFire,
    _TweakTargeting_LockFire_Corruption.LockFire
]
TweakTargeting_OuterBeamIcon = typing.Union[
    _TweakTargeting_OuterBeamIcon_Echoes.OuterBeamIcon,
    _TweakTargeting_OuterBeamIcon_Corruption.OuterBeamIcon
]
TweakTargeting_Scan = typing.Union[
    _TweakTargeting_Scan_Echoes.Scan,
    _TweakTargeting_Scan_Corruption.Scan
]
Vector2f = typing.Union[
    _Vector2f_Prime.Vector2f,
    _Vector2f_Echoes.Vector2f,
    _Vector2f_Corruption.Vector2f,
    _Vector2f_DKCReturns.Vector2f
]
VelocityConvergence = typing.Union[
    _VelocityConvergence_Corruption.VelocityConvergence,
    _VelocityConvergence_DKCReturns.VelocityConvergence
]
VisorParameters = typing.Union[
    _VisorParameters_Prime.VisorParameters,
    _VisorParameters_Echoes.VisorParameters,
    _VisorParameters_Corruption.VisorParameters
]
WeaponVulnerability = typing.Union[
    _WeaponVulnerability_Echoes.WeaponVulnerability,
    _WeaponVulnerability_Corruption.WeaponVulnerability
]
