# PROJEK MID FINAL BANGET

country_language = {
    "Afghanistan": "Persian",
    "Albania": "Albanian",
    "Algeria": "Arabic",
    "Andorra": "Catalan",
    "Angola": "Portuegese",
    "Antigua and Barbuda": "English",
    "Argentina": "Spanish",
    "Armenia": "Armenian",
    "Australia": "English",
    "Austria": "German",
    "Azerbaijan": "Azerbaijani",
    "Bahamas": "English",
    "Bahrain": "Arabic",
    "Bangladesh": "Bengali",
    "Barbados": "English",
    "Belarus": "Belarusian",
    "Belgium": "Dutch",
    "Belize": "English",
    "Benin": "French",
    "Bhutan": "Dzongkha",
    "Bolivia": "Castillian",
    "Bosnia and Herzegovina": "None",
    "Botswana": "English",
    "Brazil": "Portuguese",
    "Brunei": "Malay",
    "Bulgaria": "Bulgarian",
    "Burkina Faso": "Moore",
    "Burundi": "French",
    "Cape Verde": "Portuguese",
    "Cambodia": "Khmer",
    "Cameroon": "English",
    "Canada": "English",
    "Central African Republic": "French",
    "Chad": "Arabic",
    "Chile": "Spanish",
    "China": "Standard Chinese",
    "Colombia": "Spanish",
    "Comoros": "Comorian",
    "Democratic Republic of the Congo": "Arabic",
    "Republic of the Congo": "French",
    "Costa Rica": "Spanish",
    "Croatia": "Croatian",
    "Cuba": "Spanish",
    "Cyprus": "Greek",
    "Czech Republic": "Czech",
    "Denmark": "Danish",
    "Djibouti": "Arabic",
    "Dominica": "English",
    "Dominican Republic": "Spanish",
    "Ecuador": "Spanish",
    "Egypt": "Arabic",
    "El Salvador": "Spanish",
    "Equatorial Guinea": "French",
    "Eritrea": "Tigrinya",
    "Estonia": "Estonian",
    "Eswatini": "English",
    "Ethiopia": "Afar",
    "Fiji": "English",
    "Finland": "Finnish",
    "France": "French",
    "Gabon": "French",
    "Gambia": "English",
    "Georgia": "Georgian",
    "Germany": "German",
    "Ghana": "English",
    "Greece": "Greek",
    "Grenada": "English",
    "Guatemala": "Spanish",
    "Guinea": "French",
    "Guinea-Bissau": "Portuguese",
    "Guyana": "English",
    "Haiti": "French",
    "Honduras": "Spanish",
    "Hungary": "Hungarian",
    "Iceland": "Icelandic",
    "India": "Hindi",
    "Indonesia": "Indonesian",
    "Iran": "Persian",
    "Iraq": "Arabic",
    "Ireland": "Irish",
    "Italy": "Italian",
    "Jamaica": "English",
    "Japan": "Japenese",
    "Jordan": "Arabic",
    "Kazakhstan": "Kazakh",
    "Kenya": "English",
    "Kiribati": "English",
    "North Korea": "Korean",
    "South Korea": "Korean",
    "Kuwait": "Standard Arabic",
    "Kyrgyzstan": "Kyrgyz",
    "Laos": "Lao",
    "Latvia": "Latvian",
    "Lebanon": "Arabic",
    "Lesotho": "Sotho",
    "Liberia": "English",
    "Libya": "Arabic",
    "Liechtenstein": "German",
    "Lithuania": "Lithuanian",
    "Luxembourg": "French",
    "Madagascar": "French",
    "Malawi": "English",
    "Malaysia": "Malay",
    "Maldives": "Dhivehi",
    "Mali": "Bambara",
    "Malta": "Maltese",
    "Marshall Islands": "English",
    "Mauritania": "Arabic",
    "Mauritius": "English",
    "Mexico": "Spanish",
    "Micronesia": "English",
    "Moldova": "Romanian",
    "Monaco": "French",
    "Mongolia": "Mongolian",
    "Montenegro": "Montenegrin",
    "Morocco": "Arabic",
    "Mozambique": "Portuguese",
    "Myanmar": "Burmese",
    "Namibia": "English",
    "Nauru": "English",
    "Nepal": "Nepali",
    "Netherlands": "Dutch",
    "New Zealand": "English",
    "Nicaragua": "Spanish",
    "Niger": "French",
    "Nigeria": "English",
    "North Macedonia": "Macedonian",
    "Norway": "Norwegian",
    "Oman": "Arabic",
    "Pakistan": "Urdu",
    "Palau": "English",
    "Palestine": "Arabic",
    "Panama": "Spanish",
    "Papua New Guinea": "English",
    "Paraguay": "Spanish",
    "Peru": "Spanish",
    "Philippines": "Filipino",
    "Poland": "Polish",
    "Portugal": "Portuguese",
    "Qatar": "Arabic",
    "Romania": "Romanian",
    "Russia": "Russian",
    "Rwanda": "English",
    "Samoa": "English",
    "Saudi Arabia": "Arabic",
    "Senegal": "French",
    "Serbia": "Serbian",
    "Seychelles": "English",
    "Sierra Leone": "English",
    "Singapore": "English",
    "Slovakia": "Slovak",
    "Slovenia": "Slovene",
    "Somalia": "Somali",
    "Spain": "Spanish",
    "Sri Lanka": "Sinhala",
    "Sudan": "Arabic",
    "Sweden": "Swedish",
    "Switzerland": "French",
    "Syria": "Arabic",
    "Taiwan": "None",
    "Tajikistan": "Tajik",
    "Tanzania": "Swahili",
    "Thailand": "Central Thai",
    "Togo": "French",
    "Trinidad and Tobago" : "English",
    "Tunisia": "Arabic",
    "Turkey": "Turkish",
    "Turkmenistan": "Turkmen",
    "Tuvalu": "Tuvaluan",
    "Uganda": "English",
    "Ukraine": "Ukrainian",
    "United Arab Emirates": "Arabic",
    "United Kingdom": "English",
    "United States" : "English",
    "Uruguay": "Spanish",
    "Uzbekistan": "Uzbek",
    "Vanuatu": "English",
    "Venezuela": "Spanish",
    "Vietnam": "Vietnamese",
    "Yemen": "Arabic",
    "Zambia": "English",
    "Zimbabwe": "Chewa"
}
  
def get_country_language(country_name):
    country_name = country_name.title()
    if country_name in country_language:
        return country_language[country_name]
    else:
        return "Code not found"