# coding: utf-8

"""
    Platform External API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from platform_api_python_client.models.create_inference_deployment_v2_request import CreateInferenceDeploymentV2Request

class TestCreateInferenceDeploymentV2Request(unittest.TestCase):
    """CreateInferenceDeploymentV2Request unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateInferenceDeploymentV2Request:
        """Test CreateInferenceDeploymentV2Request
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateInferenceDeploymentV2Request`
        """
        model = CreateInferenceDeploymentV2Request()
        if include_optional:
            return CreateInferenceDeploymentV2Request(
                name = '',
                cluster_id = 56,
                hardware_instance_id = 56,
                image_url = '',
                port = 56,
                min_scale = 56,
                max_scale = 56,
                concurrency = 56,
                healthcheck = '',
                env_vars = {
                    'key' : ''
                    },
                command = [
                    ''
                    ],
                command_args = [
                    ''
                    ],
                endpoint_certificate_authority = ''
            )
        else:
            return CreateInferenceDeploymentV2Request(
                name = '',
                cluster_id = 56,
                hardware_instance_id = 56,
                image_url = '',
                port = 56,
                min_scale = 56,
                max_scale = 56,
        )
        """

    def testCreateInferenceDeploymentV2Request(self):
        """Test CreateInferenceDeploymentV2Request"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
