
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-13T16:30:06+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3743f4f6a5ef2678ca996c73ce4980da1fa87927",
 "version": "1.0.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
