
# This file was generated by 'versioneer.py' (0.22) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-12T12:52:10+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d5ed1bd4f9d03c3c1c8bec267eab99221925e116",
 "version": "1.4.1rc1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
