
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-11T11:01:30+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f11c4583df34402f7124c878bc13af2a361aa81",
 "version": "1.9.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
