from django.conf import settings

DJX_ACCOUNT = settings.DJX_ACCOUNT

USER_CONFIRMATION_TOKEN_TTL = DJX_ACCOUNT['USER_CONFIRMATION_TOKEN_TTL']
USER_PASSWORD_RESET_TOKEN_TTL = DJX_ACCOUNT['USER_PASSWORD_RESET_TOKEN_TTL']

CLIENT_USER_CONFIRMATION_TOKEN_URL = DJX_ACCOUNT["CLIENT_USER_CONFIRMATION_TOKEN_URL"]
CLIENT_USER_PASSWORD_RESET_TOKEN_URL = DJX_ACCOUNT["CLIENT_USER_PASSWORD_RESET_TOKEN_URL"]

GOOGLE_CLIENT_SECRET = DJX_ACCOUNT['GOOGLE']['CLIENT_SECRET']
GOOGLE_CLIENT_ID = DJX_ACCOUNT['GOOGLE']['CLIENT_ID']

FACEBOOK_CLIENT_ID = DJX_ACCOUNT['FACEBOOK']['CLIENT_ID']
FACEBOOK_SECRET = DJX_ACCOUNT['FACEBOOK']['CLIENT_SECRET']

MICROSOFT_CLIENT_ID = DJX_ACCOUNT['MICROSOFT']['CLIENT_ID']
MICROSOFT_SECRET = DJX_ACCOUNT['MICROSOFT']['CLIENT_SECRET']

TWITTER_API_KEY = DJX_ACCOUNT['TWITTER']['CLIENT_ID']
TWITTER_API_KEY_SECRET = DJX_ACCOUNT['TWITTER']['CLIENT_SECRET']

LINKEDIN_API_ID = DJX_ACCOUNT['LINKEDIN']['CLIENT_ID']
LINKEDIN_API_SECRET = DJX_ACCOUNT['LINKEDIN']['CLIENT_SECRET']

DISCORD_CLIENT_ID = DJX_ACCOUNT['DISCORD']['CLIENT_ID']
DISCORD_CLIENT_SECRET = DJX_ACCOUNT['DISCORD']['CLIENT_SECRET']
DISCORD_USERNAME_KEY = 'email'

DEFAULT_ADMIN_USERNAME = DJX_ACCOUNT["DEFAULT_ADMIN_USERNAME"]
DEFAULT_ADMIN_EMAIL = DJX_ACCOUNT["DEFAULT_ADMIN_EMAIL"]
DEFAULT_ADMIN_PASSWORD = DJX_ACCOUNT["DEFAULT_ADMIN_PASSWORD"]

CREATE_USER_ON_LOGIN = DJX_ACCOUNT.get("CREATE_USER_ON_LOGIN", False)

ALLOW_SESSION = DJX_ACCOUNT.get("ALLOW_SESSION", False)
USERNAME_IS_EMAIL = DJX_ACCOUNT.get("USERNAME_IS_EMAIL", True)
