"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from gsmservice_gateway import utils


class MessageType(int, Enum, metaclass=utils.OpenEnumMeta):
    r"""Message type according to the table:

    |type|Description|
    |----|-----------|
    |  1 | SMS PRO   |
    |  3 | SMS ECO   |
    |  4 | SMS 2WAY  |
    | 10 | MMS       |
    """

    SMS_PRO = 1
    SMS_ECO = 3
    SMS_TWO_WAY = 4
    MMS = 10
