
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-10T16:08:30+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "f4220ac8996d49d2d673c3675222d3558c3b9e5f",
 "version": "0.7.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
