
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T10:28:00-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "2933c1a91551ab1d848849560e9b811e6481b282",
 "version": "0.1.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
