# This file automatically generated by
#    /home/runner/work/columnar-python-client/columnar-python-client/couchbase_columnar_version.py
# at
#    2024-10-10 21:52:29.319076
__version__ = '1.0.0.dev3'
