data_country = {
    "AF": {"name": "Afghanistan", "continent": "Asia"},
    "AL": {"name": "Albania", "continent": "Europe"},
    "DZ": {"name": "Algeria", "continent": "Africa"},
    "AD": {"name": "Andorra", "continent": "Europe"},
    "AO": {"name": "Angola", "continent": "Africa"},
    "AG": {"name": "Antigua and Barbuda", "continent": "America"},
    "AR": {"name": "Argentina", "continent": "America"},
    "AM": {"name": "Armenia", "continent": "Asia"},
    "AU": {"name": "Australia", "continent": "Oceania"},
    "AT": {"name": "Austria", "continent": "Europe"},
    "AZ": {"name": "Azerbaijan", "continent": "Asia"},
    "BS": {"name": "Bahamas", "continent": "America"},
    "BH": {"name": "Bahrain", "continent": "Asia"},
    "BD": {"name": "Bangladesh", "continent": "Asia"},
    "BB": {"name": "Barbados", "continent": "America"},
    "BY": {"name": "Belarus", "continent": "Europe"},
    "BE": {"name": "Belgium", "continent": "Europe"},
    "BZ": {"name": "Belize", "continent": "America"},
    "BJ": {"name": "Benin", "continent": "Africa"},
    "BT": {"name": "Bhutan", "continent": "Asia"},
    "BO": {"name": "Bolivia", "continent": "America"},
    "BA": {"name": "Bosnia and Herzegovina", "continent": "Europe"},
    "BW": {"name": "Botswana", "continent": "Africa"},
    "BR": {"name": "Brazil", "continent": "America"},
    "BN": {"name": "Brunei", "continent": "Asia"},
    "BG": {"name": "Bulgaria", "continent": "Europe"},
    "BF": {"name": "Burkina Faso", "continent": "Africa"},
    "BI": {"name": "Burundi", "continent": "Africa"},
    "CV": {"name": "Cape Verde", "continent": "Africa"},
    "KH": {"name": "Cambodia", "continent": "Asia"},
    "CM": {"name": "Cameroon", "continent": "Africa"},
    "CA": {"name": "Canada", "continent": "America"},
    "CF": {"name": "Central African Republic", "continent": "Africa"},
    "TD": {"name": "Chad", "continent": "Africa"},
    "CL": {"name": "Chile", "continent": "America"},
    "CN": {"name": "China", "continent": "Asia"},
    "CO": {"name": "Colombia", "continent": "America"},
    "KM": {"name": "Comoros", "continent": "Africa"},
    "CG": {"name": "Republic of the Congo", "continent": "Africa"},
    "CD": {"name": "Democratic Republic of the Congo", "continent": "Africa"},
    "CR": {"name": "Costa Rica", "continent": "America"},
    "HR": {"name": "Croatia", "continent": "Europe"},
    "CU": {"name": "Cuba", "continent": "America"},
    "CY": {"name": "Cyprus", "continent": "Europe"},
    "CZ": {"name": "Czech Republic", "continent": "Europe"},
    "DK": {"name": "Denmark", "continent": "Europe"},
    "DJ": {"name": "Djibouti", "continent": "Africa"},
    "DM": {"name": "Dominica", "continent": "America"},
    "DO": {"name": "Dominican Republic", "continent": "America"},
    "EC": {"name": "Ecuador", "continent": "America"},
    "EG": {"name": "Egypt", "continent": "Africa"},
    "SV": {"name": "El Salvador", "continent": "America"},
    "GQ": {"name": "Equatorial Guinea", "continent": "Africa"},
    "ER": {"name": "Eritrea", "continent": "Africa"},
    "EE": {"name": "Estonia", "continent": "Europe"},
    "SZ": {"name": "Eswatini", "continent": "Africa"},
    "ET": {"name": "Ethiopia", "continent": "Africa"},
    "FJ": {"name": "Fiji", "continent": "Oceania"},
    "FI": {"name": "Finland", "continent": "Europe"},
    "FR": {"name": "France", "continent": "Europe"},
    "GA": {"name": "Gabon", "continent": "Africa"},
    "GM": {"name": "Gambia", "continent": "Africa"},
    "GE": {"name": "Georgia", "continent": "Europe"},
    "DE": {"name": "Germany", "continent": "Europe"},
    "GH": {"name": "Ghana", "continent": "Africa"},
    "GR": {"name": "Greece", "continent": "Europe"},
    "GD": {"name": "Grenada", "continent": "America"},
    "GT": {"name": "Guatemala", "continent": "America"},
    "GN": {"name": "Guinea", "continent": "Africa"},
    "GW": {"name": "Guinea-Bissau", "continent": "Africa"},
    "GY": {"name": "Guyana", "continent": "America"},
    "HT": {"name": "Haiti", "continent": "America"},
    "HN": {"name": "Honduras", "continent": "America"},
    "HU": {"name": "Hungary", "continent": "Europe"},
    "IS": {"name": "Iceland", "continent": "Europe"},
    "IN": {"name": "India", "continent": "Asia"},
    "ID": {"name": "Indonesia", "continent": "Asia"},
    "IR": {"name": "Iran", "continent": "Asia"},
    "IQ": {"name": "Iraq", "continent": "Asia"},
    "IE": {"name": "Ireland", "continent": "Europe"},
    "IL": {"name": "Israel", "continent": "Asia"},
    "IT": {"name": "Italy", "continent": "Europe"},
    "JM": {"name": "Jamaica", "continent": "America"},
    "JP": {"name": "Japan", "continent": "Asia"},
    "JO": {"name": "Jordan", "continent": "Asia"},
    "KZ": {"name": "Kazakhstan", "continent": "Asia"},
    "KE": {"name": "Kenya", "continent": "Africa"},
    "KI": {"name": "Kiribati", "continent": "Oceania"},
    "KP": {"name": "North Korea", "continent": "Asia"},
    "KR": {"name": "South Korea", "continent": "Asia"},
    "KW": {"name": "Kuwait", "continent": "Asia"},
    "KG": {"name": "Kyrgyzstan", "continent": "Asia"},
    "LA": {"name": "Laos", "continent": "Asia"},
    "LV": {"name": "Latvia", "continent": "Europe"},
    "LB": {"name": "Lebanon", "continent": "Asia"},
    "LS": {"name": "Lesotho", "continent": "Africa"},
    "LR": {"name": "Liberia", "continent": "Africa"},
    "LY": {"name": "Libya", "continent": "Africa"},
    "LI": {"name": "Liechtenstein", "continent": "Europe"},
    "LT": {"name": "Lithuania", "continent": "Europe"},
    "LU": {"name": "Luxembourg", "continent": "Europe"},
    "MG": {"name": "Madagascar", "continent": "Africa"},
    "MW": {"name": "Malawi", "continent": "Africa"},
    "MY": {"name": "Malaysia", "continent": "Asia"},
    "MV": {"name": "Maldives", "continent": "Asia"},
    "ML": {"name": "Mali", "continent": "Africa"},
    "MT": {"name": "Malta", "continent": "Europe"},
    "MH": {"name": "Marshall Islands", "continent": "Oceania"},
    "MR": {"name": "Mauritania", "continent": "Africa"},
    "MU": {"name": "Mauritius", "continent": "Africa"},
    "MX": {"name": "Mexico", "continent": "America"},
    "FM": {"name": "Micronesia", "continent": "Oceania"},
    "MD": {"name": "Moldova", "continent": "Europe"},
    "MC": {"name": "Monaco", "continent": "Europe"},
    "MN": {"name": "Mongolia", "continent": "Asia"},
    "ME": {"name": "Montenegro", "continent": "Europe"},
    "MA": {"name": "Morocco", "continent": "Africa"},
    "MZ": {"name": "Mozambique", "continent": "Africa"},
    "MM": {"name": "Myanmar", "continent": "Asia"},
    "NA": {"name": "Namibia", "continent": "Africa"},
    "NR": {"name": "Nauru", "continent": "Oceania"},
    "NP": {"name": "Nepal", "continent": "Asia"},
    "NL": {"name": "Netherlands", "continent": "Europe"},
    "NZ": {"name": "New Zealand", "continent": "Oceania"},
    "NI": {"name": "Nicaragua", "continent": "America"},
    "NE": {"name": "Niger", "continent": "Africa"},
    "NG": {"name": "Nigeria", "continent": "Africa"},
    "MK": {"name": "North Macedonia", "continent": "Europe"},
    "NO": {"name": "Norway", "continent": "Europe"},
    "OM": {"name": "Oman", "continent": "Asia"},
    "PK": {"name": "Pakistan", "continent": "Asia"},
    "PW": {"name": "Palau", "continent": "Oceania"},
    "PA": {"name": "Panama", "continent": "America"},
    "PG": {"name": "Papua New Guinea", "continent": "Oceania"},
    "PY": {"name": "Paraguay", "continent": "America"},
    "PE": {"name": "Peru", "continent": "America"},
    "PH": {"name": "Philippines", "continent": "Asia"},
    "PL": {"name": "Poland", "continent": "Europe"},
    "PT": {"name": "Portugal", "continent": "Europe"},
    "QA": {"name": "Qatar", "continent": "Asia"},
    "RO": {"name": "Romania", "continent": "Europe"},
    "RU": {"name": "Russia", "continent": "Europe"},
    "RW": {"name": "Rwanda", "continent": "Africa"},
    "WS": {"name": "Samoa", "continent": "Oceania"},
    "SA": {"name": "Saudi Arabia", "continent": "Asia"},
    "SN": {"name": "Senegal", "continent": "Africa"},
    "RS": {"name": "Serbia", "continent": "Europe"},
    "SC": {"name": "Seychelles", "continent": "Africa"},
    "SL": {"name": "Sierra Leone", "continent": "Africa"},
    "SG": {"name": "Singapore", "continent": "Asia"},
    "SK": {"name": "Slovakia", "continent": "Europe"},
    "SI": {"name": "Slovenia", "continent": "Europe"},
    "SO": {"name": "Somalia", "continent": "Africa"},
    "ES": {"name": "Spain", "continent": "Europe"},
    "LK": {"name": "Sri Lanka", "continent": "Asia"},
    "SD": {"name": "Sudan", "continent": "Africa"},
    "SY": {"name": "Syria", "continent": "Asia"},
    "SE": {"name": "Sweden", "continent": "Europe"},
    "CH": {"name": "Switzerland", "continent": "Europe"},
    "TW": {"name": "Taiwan", "continent": "Asia"},
    "TJ": {"name": "Tajikistan", "continent": "Asia"},
    "TZ": {"name": "Tanzania", "continent": "Africa"},
    "TH": {"name": "Thailand", "continent": "Asia"},
    "TG": {"name": "Togo", "continent": "Africa"},
    "TT": {"name": "Trinidad and Tobago", "continent": "America"},
    "TN": {"name": "Tunisia", "continent": "Africa"},
    "TR": {"name": "Turkey", "continent": "Asia"},
    "TM": {"name": "Turkmenistan", "continent": "Asia"},
    "TV": {"name": "Tuvalu", "continent": "Oceania"},
    "UG": {"name": "Uganda", "continent": "Africa"},
    "UA": {"name": "Ukraine", "continent": "Europe"},
    "AE": {"name": "United Arab Emirates", "continent": "Asia"},
    "US": {"name": "United States", "continent": "America"},
    "GB": {"name": "United Kingdom", "continent": "Europe"},
    "UY": {"name": "Uruguay", "continent": "America"},
    "UZ": {"name": "Uzbekistan", "continent": "Asia"},
    "VU": {"name": "Vanuatu", "continent": "Oceania"},
    "VE": {"name": "Venezuela", "continent": "America"},
    "VN": {"name": "Vietnam", "continent": "Asia"},
    "YE": {"name": "Yemen", "continent": "Asia"},
    "ZM": {"name": "Zambia", "continent": "Africa"},
    "ZW": {"name": "Zimbabwe", "continent": "Africa"}
}

def get_info_by_country_code(country_code):
    info = data_country.get(country_code.upper())
    if info:
        return info["name"], info["continent"]
    else:
        return "Country code not found", "Continent not found"

def get_info_by_country_name(country_name):
    for info in data_country.values():
        if info["name"].lower() == country_name.lower():
            return info["name"], info["continent"]
    return "Country name not found", "Continent not found"