
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T14:16:54+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "87602e11a8c0cd2162ed089e0477de7e65192714",
 "version": "1.8.46"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
