# your_package/__init__.py

"""
Your Package Name: Sorting Algorithms Library
Description: A collection of sorting algorithms implemented in Python.
"""

# Import the sorting functions from the sorting module
from .sorting_algorithms import (
    merge_sort,
    quick_sort,
    bubble_sort,
    insertion_sort,
    selection_sort,
    heap_sort,
    shell_sort,
    counting_sort,
    radix_sort,
    bucket_sort,
    comb_sort,
    cocktail_sort,
    gnome_sort,
    cycle_sort,
    pigeonhole_sort,
    strand_sort,
    pancake_sort,
    bogo_sort,
    stooge_sort,
    tim_sort,
    read_numbers,
    sort_numbers,
    format_output,
    allsort,
    allformat,
    write_to_file,
    comb_sort,
    shell_sort,
    counting_sort,
    introsort,
    bitonic_sort,
    odd_even_sort,
    tree_sort,
    patience_sort,
    smooth_sort,
    tournament_sort,
    library_sort,
    block_sort,
    double_selection_sort,
    spaghetti_sort,
    brick_sort,
    cycle_sort_optimized,
    exchange_sort,
    permutation_sort,
    sleep_sort,
    tag_sort,
    binary_insertion_sort,
    franceschini_sort,
    j_sort,
    slow_sort
)

__all__ = [
    "merge_sort",
    "quick_sort",
    "bubble_sort",
    "insertion_sort",
    "selection_sort",
    "heap_sort",
    "shell_sort",
    "counting_sort",
    "radix_sort",
    "bucket_sort",
    "comb_sort",
    "cocktail_sort",
    "gnome_sort",
    "cycle_sort",
    "pigeonhole_sort",
    "strand_sort",
    "pancake_sort",
    "bogo_sort",
    "stooge_sort",
    "tim_sort",
    "read_numbers",
    "sort_numbers",
    "format_output",
    "allsort",
    "allformat",
    "write_to_file",  # Добавлена новая функция
    "comb_sort",
    "shell_sort",
    "counting_sort",
    "introsort",
    "bitonic_sort",
    "odd_even_sort",
    "tree_sort",
    "patience_sort",
    "smooth_sort",
    "tournament_sort",
    "library_sort",
    "block_sort",
    "double_selection_sort",
    "spaghetti_sort",
    "brick_sort",
    "cycle_sort_optimized",
    "exchange_sort",
    "permutation_sort",
    "sleep_sort",
    "tag_sort",
    "binary_insertion_sort",
    "franceschini_sort",
    "j_sort",
    "slow_sort"
]

__version__ = "0.1.1"  # Обновлен номер версии