
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-14T10:26:00+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "d0b9fa2d6571db1e9fe9b2066a4a2737fc9fcb98",
 "version": "2.6.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
