
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-12T17:34:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "2bb3755ade11d66ac430cea730335de82e74d1d2",
 "version": "1.82.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
