
# DO NOT EDIT THIS FILE -- AUTOGENERATED BY PANTS
# Target: envoy.ci.report:package

from setuptools import setup

setup(**{
    'author': 'Ryan Northey',
    'author_email': 'ryan@synca.io',
    'description': '"Release publishing tool used in Envoy proxy\'s CI"',
    'entry_points': {
        'console_scripts': [
            'envoy.ci.report=envoy.ci.report:cmd',
        ],
    },
    'install_requires': (
        'abstracts>=0.0.12',
        'aio.api.github>=0.2.10',
        'aio.core>=0.10.5',
        'aio.run.runner>=0.3.4',
    ),
    'license': 'Apache Software License 2.0',
    'long_description': """
envoy.ci.report
==========================

Release publishing tool used in Envoy proxy's CI
""",
    'maintainer': 'Ryan Northey',
    'maintainer_email': 'ryan@synca.io',
    'name': 'envoy.ci.report',
    'namespace_packages': (
    ),
    'package_data': {
        'envoy.ci.report': (
            'py.typed',
        ),
    },
    'packages': (
        'envoy.ci.report',
        'envoy.ci.report.abstract',
    ),
    'python_requires': '>=3.10.0',
    'url': 'https://github.com/envoyproxy/toolshed/tree/main/envoy.ci.report',
    'version': '0.0.3',
})
