# This file was generated by liblab | https://liblab.com/

from __future__ import annotations

from typing import List

from .engagement_stats_row import EngagementStatsRow
from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class EngagementStats(BaseModel):
    """EngagementStats

    :param rows: rows, defaults to None
    :type rows: List[EngagementStatsRow], optional
    """

    def __init__(self, rows: List[EngagementStatsRow] = None):
        """EngagementStats

        :param rows: rows, defaults to None
        :type rows: List[EngagementStatsRow], optional
        """
        if rows is not None:
            self.rows = self._define_list(rows, EngagementStatsRow)
