# This file was generated by liblab | https://liblab.com/

from __future__ import annotations

from .upload_metadata import UploadMetadata
from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class VideoFetch(BaseModel):
    """VideoFetch

    :param metadata: metadata
    :type metadata: UploadMetadata
    :param url: url where the video to be fetched is located.
    :type url: str
    """

    def __init__(self, metadata: UploadMetadata, url: str):
        """VideoFetch

        :param metadata: metadata
        :type metadata: UploadMetadata
        :param url: url where the video to be fetched is located.
        :type url: str
        """
        self.metadata = self._define_object(metadata, UploadMetadata)
        self.url = url
