# This file was generated by liblab | https://liblab.com/

from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class AudioTrackCreate(BaseModel):
    """AudioTrackCreate

    :param file: File to upload.
    :type file: bytes
    :param lang_code: Language of the audio track. Language must be valid BCP 47.
    :type lang_code: str
    :param title: Title of the audio track.
    :type title: str
    """

    def __init__(self, file: bytes, lang_code: str, title: str):
        """AudioTrackCreate

        :param file: File to upload.
        :type file: bytes
        :param lang_code: Language of the audio track. Language must be valid BCP 47.
        :type lang_code: str
        :param title: Title of the audio track.
        :type title: str
        """
        self.file = file
        self.lang_code = self._define_str(
            "lang_code", lang_code, min_length=2, max_length=2
        )
        self.title = self._define_str("title", title, max_length=64)
