# This file was generated by liblab | https://liblab.com/

from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({"id_": "id"})
class Poster(BaseModel):
    """Poster

    :param cdn_link: Link to the poster image. URL expires after 24 hours by default.
    :type cdn_link: str
    :param default: If the poster is the default one.
    :type default: bool
    :param id_: ID of the poster.
    :type id_: int
    """

    def __init__(self, cdn_link: str, default: bool, id_: int):
        """Poster

        :param cdn_link: Link to the poster image. URL expires after 24 hours by default.
        :type cdn_link: str
        :param default: If the poster is the default one.
        :type default: bool
        :param id_: ID of the poster.
        :type id_: int
        """
        self.cdn_link = cdn_link
        self.default = default
        self.id_ = id_
