# This file was generated by liblab | https://liblab.com/

from __future__ import annotations

from typing import List

from .preset import Preset
from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class PresetList(BaseModel):
    """PresetList

    :param rows: rows
    :type rows: List[Preset]
    """

    def __init__(self, rows: List[Preset]):
        """PresetList

        :param rows: rows
        :type rows: List[Preset]
        """
        self.rows = self._define_list(rows, Preset)
