# This file was generated by liblab | https://liblab.com/

from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class ProjectCreate(BaseModel):
    """ProjectCreate

    :param title: Title of the project.
    :type title: str
    """

    def __init__(self, title: str):
        """ProjectCreate

        :param title: Title of the project.
        :type title: str
        """
        self.title = self._define_str("title", title, max_length=64)
