# This file was generated by liblab | https://liblab.com/

from __future__ import annotations

from typing import List

from .text_track import TextTrack
from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class TextTrackList(BaseModel):
    """TextTrackList

    :param rows: rows
    :type rows: List[TextTrack]
    """

    def __init__(self, rows: List[TextTrack]):
        """TextTrackList

        :param rows: rows
        :type rows: List[TextTrack]
        """
        self.rows = self._define_list(rows, TextTrack)
