# This file was generated by liblab | https://liblab.com/

from .utils.base_model import BaseModel
from .utils.json_map import JsonMap


@JsonMap({})
class WebhookCreate(BaseModel):
    """WebhookCreate

    :param url: url where you want your webhooks to be delivered. Must use https.
    :type url: str
    """

    def __init__(self, url: str):
        """WebhookCreate

        :param url: url where you want your webhooks to be delivered. Must use https.
        :type url: str
        """
        self.url = url
