
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-12T00:29:59-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a3e1605fe5d583ec85fd487097a4f222ebadb95",
 "version": "0.34.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
