# coding: utf-8

"""
    MetaCopier API

    Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metacopier_api.models.feature_dto import FeatureDTO

class TestFeatureDTO(unittest.TestCase):
    """FeatureDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeatureDTO:
        """Test FeatureDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeatureDTO`
        """
        model = FeatureDTO()
        if include_optional:
            return FeatureDTO(
                account_id = '',
                copier_id = '',
                created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                project_id = '',
                setting = metacopier_api.models.feature_setting_dto.FeatureSettingDTO(),
                type = metacopier_api.models.feature_type_dto.FeatureTypeDTO(
                    id = 56, 
                    name = '', 
                    plan_name = '', )
            )
        else:
            return FeatureDTO(
                setting = metacopier_api.models.feature_setting_dto.FeatureSettingDTO(),
                type = metacopier_api.models.feature_type_dto.FeatureTypeDTO(
                    id = 56, 
                    name = '', 
                    plan_name = '', ),
        )
        """

    def testFeatureDTO(self):
        """Test FeatureDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
