# coding: utf-8

"""
    MetaCopier API

    Explore the power of the MetaCopier API! Our RESTful API offers scalable and secure access to accounts, projects, and more. Get started quickly with authentication, explore endpoints, and access code samples in various languages.<br/><br/>All dates are in ISO 8601<br/><br/>This API is not designed for real-time communication purposes. For instance, continuously polling account information such as open positions every second is not recommended.<br/><br/>Our frontend uses this API, so you can look at the requests on our frontend for examples.

    The version of the OpenAPI document: 0.9.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from metacopier_api.api.account_api_api import AccountAPIApi


class TestAccountAPIApi(unittest.TestCase):
    """AccountAPIApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AccountAPIApi()

    def tearDown(self) -> None:
        pass

    def test_create_account(self) -> None:
        """Test case for create_account

        Create an account
        """
        pass

    def test_create_account_feature(self) -> None:
        """Test case for create_account_feature

        Create an account feature
        """
        pass

    def test_create_copier(self) -> None:
        """Test case for create_copier

        Create an account copier
        """
        pass

    def test_create_copier_feature(self) -> None:
        """Test case for create_copier_feature

        Create a copier feature
        """
        pass

    def test_create_risk_limit(self) -> None:
        """Test case for create_risk_limit

        Create an account risk limit
        """
        pass

    def test_delete_account(self) -> None:
        """Test case for delete_account

        Delete an account
        """
        pass

    def test_delete_account_feature(self) -> None:
        """Test case for delete_account_feature

        Delete an account feature
        """
        pass

    def test_delete_copier(self) -> None:
        """Test case for delete_copier

        Delete an account copier
        """
        pass

    def test_delete_copier_feature(self) -> None:
        """Test case for delete_copier_feature

        Delete a copier feature
        """
        pass

    def test_delete_risk_limit(self) -> None:
        """Test case for delete_risk_limit

        Delete an account risk limit
        """
        pass

    def test_get_account(self) -> None:
        """Test case for get_account

        Get an account
        """
        pass

    def test_get_account_copier_current_symbol_mappings(self) -> None:
        """Test case for get_account_copier_current_symbol_mappings

        Get account copier current symbol mappings
        """
        pass

    def test_get_account_feature(self) -> None:
        """Test case for get_account_feature

        Get an account feature
        """
        pass

    def test_get_account_features(self) -> None:
        """Test case for get_account_features

        Get all account features
        """
        pass

    def test_get_account_logs(self) -> None:
        """Test case for get_account_logs

        Get account logs
        """
        pass

    def test_get_accounts(self) -> None:
        """Test case for get_accounts

        Get all accounts
        """
        pass

    def test_get_copier(self) -> None:
        """Test case for get_copier

        Get account copier
        """
        pass

    def test_get_copier_feature(self) -> None:
        """Test case for get_copier_feature

        Get a copier feature
        """
        pass

    def test_get_copier_features(self) -> None:
        """Test case for get_copier_features

        Get all copier features
        """
        pass

    def test_get_copiers(self) -> None:
        """Test case for get_copiers

        Get account copiers
        """
        pass

    def test_get_risk_limit(self) -> None:
        """Test case for get_risk_limit

        Get an account risk limit
        """
        pass

    def test_get_risk_limits(self) -> None:
        """Test case for get_risk_limits

        Get account risk limits
        """
        pass

    def test_reset_risk_limit(self) -> None:
        """Test case for reset_risk_limit

        Reset an account risk limit
        """
        pass

    def test_start_account(self) -> None:
        """Test case for start_account

        Start an account (connect)
        """
        pass

    def test_stop_account(self) -> None:
        """Test case for stop_account

        Stop an account (disconnect)
        """
        pass

    def test_update_account(self) -> None:
        """Test case for update_account

        Update an account
        """
        pass

    def test_update_account_feature(self) -> None:
        """Test case for update_account_feature

        Update an account feature
        """
        pass

    def test_update_copier(self) -> None:
        """Test case for update_copier

        Update an account copier
        """
        pass

    def test_update_copier_feature(self) -> None:
        """Test case for update_copier_feature

        Update a copier feature
        """
        pass

    def test_update_risk_limit(self) -> None:
        """Test case for update_risk_limit

        Update an account risk limit
        """
        pass


if __name__ == '__main__':
    unittest.main()
