normal = [
  "Do you believe in love at first sight, or should I walk by again?",
  "Is your name Google? Because you have everything I’m searching for.",
  "If you were a vegetable, you’d be a cute-cumber!",
  "Is your dad a baker? Because you’re a cutie pie!",
  "Do you have a map? I keep getting lost in your eyes.",
  "Are you a magician? Because every time I look at you, everyone else disappears.",
  "Can you lend me a kiss? I promise I’ll give it back.",
  "If beauty were a crime, you’d be serving a life sentence.",
  "Are you Wi-Fi? Because I’m feeling a connection.",
  "Excuse me, but I think you dropped something: my jaw!",
  "Is your aura made of copper and tellurium? Because you’re Cu-Te!",
  "Do you like raisins? How do you feel about a date?",
  "Are you from Tennessee? Because you’re the only ten I see!",
  "Is your name Chapstick? Because you’re da balm!",
  "Do you have a Band-Aid? Because I just scraped my knee falling for you.",
  "You must be a magician, because every time I look at you, everyone else disappears.",
  "If you were a fruit, you’d be a fine-apple.",
  "Do you have a sunburn, or are you always this hot?",
  "I must be a snowflake because I’ve fallen for you.",
  "If looks could kill, you’d be a weapon of mass destruction.",
  "Are you a time traveler? Because I can see you in my future.",
  "Your hand looks heavy—can I hold it for you?",
  "If I could rearrange the alphabet, I’d put U and I together.",
  "You must be tired because you’ve been running through my mind all day.",
  "Is it hot in here, or is it just you?",
  "If I had a star for every time I saw you, I’d be holding the entire galaxy.",
  "Do you believe in fate? Because I think we were meant to meet.",
  "Is your name Dunkin? Because you’re looking like a hot one!",
  "Can I follow you home? Because my parents always told me to follow my dreams.",
  "You must be made of copper and tellurium because you’re Cu-Te.",
  "Are you a loan from a bank? Because you have my interest.",
  "Is your name Wi-Fi? Because I’m really feeling a connection.",
  "Do you have a pencil? Because I want to erase your past and write our future.",
  "If kisses were snowflakes, I’d send you a blizzard.",
  "You’re so sweet, you’re giving me a toothache.",
  "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you.",
  "Did it hurt? When you fell from heaven?",
  "I must be in a museum, because you’re a work of art.",
  "Do you have any raisins? No? How about a date?",
  "Are you made of bologna? Because you’re bologna-ing to me.",
  "You must be a campfire, because you’re hot and I want s’more.",
  "If you were a song, you’d be the best track on the album.",
  "Are you French? Because Eiffel for you.",
  "Do you know what would look great on you? Me.",
  "Are you a beaver? Because daaaaam.",
  "If you were a triangle, you’d be acute one.",
  "You must be a keyboard, because you’re just my type.",
  "Are we at the airport? Because my heart is taking off.",
  "I was blinded by your beauty... I’m going to need your name and number for insurance purposes.",
  "If I could be any part of you, I’d be your heart.",
]

crazy = [
  "Do you have a Band-Aid? Because I just scraped my knee falling for your craziness!",
  "Are you a time traveler? Because I can see you in my future, and it looks wild!",
  "If you were a vegetable, you’d be a ‘cute-cumber’ salad with extra dressing!",
  "Do you have an extra heart? Mine was just stolen by your craziness!",
  "If you were a fruit, you’d be a ‘fine-apple’ with a side of nuts!",
  "Are you an alien? Because you just abducted my heart and took it to your planet!",
  "Can I follow you home? Because my parents always told me to follow my dreams, and you look like one wild ride!",
  "Is your name Google? Because you’ve got everything I’m looking for, and then some!",
  "You must be a magician, because whenever I look at you, everyone else disappears into a black hole of wonder!",
  "Are you a campfire? Because you’re hot, and I want s’more crazy adventures with you!",
  "Is your aura made of glitter? Because you shine brighter than a disco ball at a rave!",
  "If you were a chicken, you’d be a ‘funny clucker’ with a side of laughter!",
  "Are you a parking ticket? Because you’ve got ‘FINE’ written all over you, and I’m ready to pay up!",
  "If you were a taco, you’d be the ‘spiciest one’ on the menu!",
  "I must be a snowflake because I’ve fallen for your crazy vibe!",
  "Is your name Wi-Fi? Because I’m feeling a connection that’s out of this world!",
  "You must be a dictionary because you’re adding meaning to my life with every crazy word you say!",
  "If you were a song, you’d be a ‘crazy anthem’ that I can’t stop dancing to!",
  "Do you believe in love at first sight, or should I walk by again and bring my disco ball?",
  "If you were a superhero, your power would be making everyone around you laugh uncontrollably!",
  "Are you made of copper and tellurium? Because you’re Cu-Te and a little insane!",
  "If you were a donut, you’d be the ‘glazed and confused’ kind, because you’ve got me spinning!",
  "Is your dad a boxer? Because you’re a knockout with a wild punch of charisma!",
  "Are you a magician? Because every time I look at you, I disappear into a world of wonder!",
  "If you were a smoothie, you’d be the ‘crazy concoction’ that I can’t resist sipping on!",
  "Are you a beaver? Because daaaaam, you’re crazy cute!",
  "If you were a meme, you’d be the ‘hilarious one’ that keeps popping up in my feed!",
  "Do you have a mirror in your pocket? Because I can see myself getting crazy with you!",
  "Are you a fruitcake? Because you’re a little nutty, but I can’t resist you!",
  "If you were a book, you’d be a ‘crazy bestseller’ that I can’t put down!",
  "Are you a cupcake? Because you’re sweet, a little nutty, and totally irresistible!",
  "If we were both socks, we’d be a ‘crazy pair’ that nobody could separate!",
  "Are you an oven? Because you’re hot and I want to turn you up!",
  "If you were a ghost, you’d be the ‘funny one’ that keeps haunting my dreams!",
  "Are you a cheese? Because you’re looking gouda tonight, and that’s a little crazy!",
  "Do you have a map? Because I just got lost in your crazy smile!",
  "If you were a superhero, you’d be ‘Captain Crazy’ with the power to make everyone laugh!",
  "Is your name Chapstick? Because you’re da balm of my crazy dreams!",
  "If you were a salad, you’d be a ‘crazy mix’ of all my favorite ingredients!",
  "Are you a light bulb? Because you light up my world in the most outrageous ways!",
  "If you were a car, you’d be a ‘crazy convertible’ that I can’t wait to take for a spin!",
  "Do you like raisins? How do you feel about a date that’s a little wild?",
  "If you were a piece of furniture, you’d be a ‘crazy recliner’ that I want to lounge on forever!",
  "Are you an artist? Because you just painted my world in the craziest colors!",
  "If you were a drink, you’d be a ‘crazy cocktail’ that leaves me wanting more!",
  "Are you a puzzle? Because I’m trying to piece together the crazy connection we have!",
  "If you were a movie, you’d be the ‘wild blockbuster’ that everyone wants to see!",
  "Are you a snowstorm? Because you make my heart race with every flurry of fun!",
  "If you were a bed, you’d be the ‘crazy comfy’ kind that I never want to leave!",
  "Are you a time bomb? Because you’re making my heart explode with excitement!",
]

en_flirts = {
  "normal": normal,
  "crazy": crazy,
  "all": normal + crazy,
}
