normal = [
  "Tumhari smile toh mera din bana deti hai.",
  "Tumse milkar aisa lagta hai jaise dream come true ho gaya.",
  "Kya tumhe pata hai? Tum smile karti ho toh world aur zyada beautiful lagti hai.",
  "Tumhare saath time guzarne ka mann karta hai... hamesha.",
  "Tumhe dekh kar lagta hai ki main ne kuch accha kaam kiya hoga pichle janam mein.",
  "Tum meri life ka wo song ho jo main baar-baar repeat pe sunna chahta hoon.",
  "Tumhari aankhon mein kuch toh magic hai, jo mujhe har baar hypnotize kar deti hai.",
  "Tum ho toh lagta hai duniya ki har cheez perfect hai.",
  "Tumhare bina toh life thodi incomplete si lagti hai.",
  "Tumhare bina din bilkul boring lagta hai, but tum ho toh sab kuch exciting!",
  "Tum meri favorite notification ho.",
  "Tumhara naam phone ki screen pe dekhte hi heart beat fast ho jati hai.",
  "Tumhara saath mil jaye toh bas, aur kuch nahi chahiye.",
  "Tumhare saath time slow ho jata hai, aur ye ekdum perfect lagta hai.",
  "Tumhari baaton mein ek alag hi sweetness hai, jo aur kahin nahi milti.",
  "Agar tumhari muskaan ek crime hoti, toh tumhe life imprisonment milti!",
  "Tumhare bina coffee bhi pheeki lagti hai.",
  "Tumhari selfie toh meri day bright kar deti hai.",
  "Tumhe pata hai, jab tum blush karti ho, tum aur bhi zyada cute lagti ho.",
  "Tumhara style alag hai, sabse unique, sabse best.",
  "Tumhari aankhon mein kho jaana mera favorite hobby ban gaya hai.",
  "Tumhare saath baat karte waqt time ka pata hi nahi chalta.",
  "Tumhari voice toh ek perfect melody ki tarah hai.",
  "Tumhari harkatein meri dil ki dhadkano ko fast kar deti hain.",
  "Tumhare liye jitne tareef karun, wo kam hi padenge.",
  "Tum itni amazing ho ki kabhi-kabhi lagta hai ki sapna dekh raha hoon.",
  "Tumhara hath pakadne ka mann karta hai, aur kabhi chhodne ka nahi.",
  "Tumhe dekh kar hamesha yahi sochta hoon, how can someone be this perfect?",
  "Tumhare bina sab kuch incomplete lagta hai, jaise koi puzzle ka missing piece.",
  "Tumhari baatein mere dil ko ekdum khush kar deti hain.",
  "Tumhari presence hi meri duniya brighten up kar deti hai.",
  "Tumhari har ek ada ka fan hoon main.",
  "Tumhari aankhen kitni expressive hain, jaise sab kuch keh jaati hain.",
  "Tumhare saath har ek moment magical lagta hai.",
  "Tum ho toh life mein har ek din ek special occasion ban jata hai.",
  "Tum meri life ki sunshine ho.",
  "Tumhari baaton mein ek aisi warmth hai jo dil ko choo jaati hai.",
  "Tum ho toh sab kuch complete lagta hai.",
  "Tumhara naam hi meri favorite word ban gaya hai.",
  "Tum itni special ho ki tumhare bina sab kuch boring lagta hai.",
  "Tumhari aankhon mein dekha toh bas kho gaya.",
  "Tumhare saath hoon toh sab kuch easy lagta hai.",
  "Tumhari ek smile ke liye kuch bhi kar sakta hoon.",
  "Tumhara pyaar meri zindagi ka sabse khoobsurat feeling hai.",
  "Tumhare saath har ek moment unforgettable ban jata hai.",
  "Tumhari aankhon mein kuch toh secret hai, jo har baar curious banata hai.",
  "Tumhara saath toh meri zindagi ka best surprise hai.",
  "Tumhari aankhen wo kitaab hai, jise main baar baar padhna chahta hoon.",
  "Tum jo ho, bas perfect ho, aur kuch kehne ki zaroorat nahi.",
  "Tumhari vibes mere dil ko ekdum relax kar deti hain.",
]

crazy = [
  "Tumhari aankhon mein toh Google Maps bhi kho jaye.",
  "Tumhara smile toh GPS ka signal lagta hai, hamesha dil tak seedha raste dikhata hai.",
  "Tum itni sundar ho ki mera dil ‘out of service’ mode mein chala gaya.",
  "Tumhara naam sunte hi meri heartbeat fast-forward pe chal jaati hai.",
  "Tumhe dekh kar lagta hai ki mera system reboot ho gaya hai, tumne mujhe crash kar diya!",
  "Tumhari vibes toh kisi high-speed Wi-Fi se bhi tez hain, sab kuch connect kar deti hain.",
  "Tumhari selfie dekhkar main toh flat ho gaya, ab bas tumhare love ka mattress chahiye.",
  "Tum itni cute ho ki mera dil lagta hai ice cream ban gaya, tumhari smile dekh kar melt ho raha hai.",
  "Tumhari aankhon mein dekha aur lagta hai mera software hang ho gaya!",
  "Tum jo baat karti ho, lagta hai Netflix ka next episode hai, aur main 'next' daba nahi sakta.",
  "Tumhari awaaz toh meri ringtone ban chuki hai, bas repeat mode pe!",
  "Tum jo muskura deti ho, toh lagta hai ki mere dil ne turbo boost laga liya.",
  "Tumhara style toh mera system crash kar raha hai, reboot ka chance hi nahi milta!",
  "Tum itni hot ho ki AC bhi cool nahi kar paa raha.",
  "Tumhare saath waqt kaise guzarta hai, lagta hai jaise fast forward mein hoon.",
  "Tumhari aankhon ka password kya hai? Mujhe unhe unlock karna hai!",
  "Tum ho toh lagta hai duniya ka har traffic signal green ho gaya.",
  "Tum itni zyada bright ho ki lagta hai mujhe sunglasses pehn lene chahiye.",
  "Tumhari smile ne mere system ki firewall disable kar di.",
  "Tumhare bina toh zindagi pop-up ads se bhari padi hai—no skip button!",
  "Tum jo bhi pehno, lagta hai runway pe chal rahi ho, kitni fashion icon ho!",
  "Tumhari aankhen itni deep hain ki main unmein drown ho jaata hoon.",
  "Tumhara sense of humor itna sharp hai, lagta hai tumne punchlines ka PhD kiya hai.",
  "Tum jo ho, ekdum VIP ho, mere life ke premium section mein.",
  "Tumhe dekhte hi mera internet lag ho gaya, itni bandwidth consume karti ho.",
  "Tum jo smile karti ho, toh lagta hai jaise mera screen brightness max ho gaya.",
  "Tumhare bina life jaise aeroplane mode pe chali gayi ho."
  "Tumhari ek selfie meri battery ko 100% charge kar deti hai.",
  "Tumhari aankhon mein dekha aur lagta hai maine duniya ka best filter laga liya.",
  "Tum itni stunning ho, lagta hai mujhe zoom karke close-up lena padega.",
  "Tumhari baatein toh itni sweet hain ki diabetes ho sakti hai.",
  "Tumhari ek look kaafi hai, mera dil delete aur refresh hone ke liye.",
  "Tum itni cute ho ki teddy bears tumse jealous ho rahe hain.",
  "Tumhare saath waqt bitana jaise VIP access ho life ke sabse best moments ka.",
  "Tumhari aankhen toh wo secret hai jise main decode karne ke liye ready hoon.",
  "Tumhara pyaar meri zindagi ki hard drive pe sabse important file hai.",
  "Tumhare bina life jaise ek slow internet connection lagta hai, koi kaam nahi hota!",
  "Tumhari vibes mere brain ka processor overheat kar deti hain.",
  "Tumhari baaton mein aisa charm hai, jaise tum hacker ho aur mera dil hack kar diya hai.",
  "Tum itni perfect ho, lagta hai tumhe Photoshop ki zarurat nahi.",
  "Tumhare saath rah kar life ke sab glitches fix ho jaate hain.",
  "Tumhara sense of humor itna cool hai ki mere dil ko thoda chill kar raha hai.",
  "Tumhari aankhon mein poora universe hai, aur main usme travel karna chahta hoon.",
  "Tumhare bina toh zindagi jaise ek unsaved document lagti hai, risky!",
  "Tum itni khoobsurat ho ki main tumhe ek art gallery mein frame karna chahta hoon.",
  "Tumhari energy lagta hai, ek cup strong coffee se zyada hai!",
  "Tum itni zyada sweet ho, mujhe lagta hai sugar rush ho gaya hai.",
  "Tumhari aankhon ki brightness se meri life ekdum clear ho gayi hai.",
  "Tumhare bina life jaise ek paused movie lagti hai, play button chahiye tumhara.",
]


he_flirts = {
  "normal": normal,
  "crazy": crazy,
  "all": normal + crazy,
}
