
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-13T16:35:12+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7e6e0f815149d4894cc3c7c1aa2f8b92cb7f02f8",
 "version": "8.22.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
