
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-11T18:12:23+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "d1f33aac8cedd81790796713ee790b3a7cc0888f",
 "version": "0.23.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
