# generated by datamodel-codegen:
#   filename:  webGlLayer.json
#   timestamp: 2024-10-14T13:45:10+00:00

from __future__ import annotations

from typing import List, Optional, Union

from pydantic import BaseModel, ConfigDict, Field, confloat


class IWebGlLayer(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    source: str = Field(..., description='The id of the source')
    opacity: Optional[confloat(ge=0.0, le=1.0, multiple_of=0.1)] = Field(
        1, description='The opacity of the source'
    )
    color: Optional[
        Union[
            str,
            float,
            List[Union[str, float, List[Union[float, str, List[Union[float, str]]]]]],
        ]
    ] = Field(None, description='The color of the the object')
