# coding: utf-8

"""
    seqq

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.18
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from seqq.models.v1alpha_code import V1alphaCode

class TestV1alphaCode(unittest.TestCase):
    """V1alphaCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testV1alphaCode(self):
        """Test V1alphaCode"""
        # inst = V1alphaCode()

if __name__ == '__main__':
    unittest.main()
