
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-11T19:24:30-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "dc0e5745f1453f6c587e6ea8c7f794a90c192be2",
 "version": "0.9.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
