
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-11T08:54:52-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb02461eeebf8f648ea85591bc98c81c7cec1e4b",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
