# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
import typing
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ShareLocation(UniversalBaseModel):
    title: str = pydantic.Field()
    """
    The title for the share location action. Maximum length is 25 characters.
    """

    action_type: typing.Literal["share_location"] = pydantic.Field(default="share_location")
    """
    The type of action being sent
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
