# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .phone_number import PhoneNumber
import pydantic
import typing
from .sms_message import SmsMessage
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class Sms(UniversalBaseModel):
    phone_number: PhoneNumber = pydantic.Field()
    """
    Phone number to send the SMS message to
    """

    message_type: typing.Literal["sms"] = pydantic.Field(default="sms")
    """
    The type of message being sent
    """

    message: SmsMessage = pydantic.Field()
    """
    The content of the message
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
