# coding: utf-8

"""
    FilterLists Directory API

    An ASP.NET Core API serving the core FilterList information.

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from filterlists_api.models.filter_lists_directory_application_queries_get_tags_response import FilterListsDirectoryApplicationQueriesGetTagsResponse

class TestFilterListsDirectoryApplicationQueriesGetTagsResponse(unittest.TestCase):
    """FilterListsDirectoryApplicationQueriesGetTagsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FilterListsDirectoryApplicationQueriesGetTagsResponse:
        """Test FilterListsDirectoryApplicationQueriesGetTagsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FilterListsDirectoryApplicationQueriesGetTagsResponse`
        """
        model = FilterListsDirectoryApplicationQueriesGetTagsResponse()
        if include_optional:
            return FilterListsDirectoryApplicationQueriesGetTagsResponse(
                id = 2,
                name = 'ads',
                description = 'Blocks advertisements',
                filter_list_ids = [1,3,6]
            )
        else:
            return FilterListsDirectoryApplicationQueriesGetTagsResponse(
        )
        """

    def testFilterListsDirectoryApplicationQueriesGetTagsResponse(self):
        """Test FilterListsDirectoryApplicationQueriesGetTagsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
