# coding: utf-8

"""
    FilterLists Directory API

    An ASP.NET Core API serving the core FilterList information.

    The version of the OpenAPI document: v1
    Contact: b72d8917-851f-4864-ad5c-61630408048d@gb4emlsep.anonaddy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "filterlists-api"
VERSION = "1.0.6"
PYTHON_REQUIRES = ">= 3.8"
REQUIRES = [
    "urllib3 >= 1.25.3, < 3.0.0",
    "python-dateutil >= 2.8.2",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="FilterLists Directory API",
    author="Aaron Colichia",
    author_email="b72d8917-851f-4864-ad5c-61630408048d@gb4emlsep.anonaddy.com",
    url="",
    keywords=["OpenAPI", "OpenAPI-Generator", "FilterLists Directory API"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    license="MIT License",
    long_description_content_type='text/markdown',
    long_description="""\
    An ASP.NET Core API serving the core FilterList information.
    """,  # noqa: E501
    package_data={"filterlists_api": ["py.typed"]},
)
