normal = [
  "¿Crees en el amor a primera vista, o debo pasar otra vez?",
  "Si fueras una lágrima, no lloraría por miedo a perderte.",
  "Contigo, cada día es un buen día.",
  "¿Tienes un mapa? Me perdí en tus ojos.",
  "Eres tan dulce que me has dado una sobredosis de azúcar.",
  "Si la belleza fuera un crimen, estarías en prisión de por vida.",
  "¿Sabes que tienes algo en común con el sol? Iluminas mi mundo.",
  "Eres como un sueño del que no quiero despertar.",
  "No soy fotógrafo, pero puedo imaginarnos juntos.",
  "Tienes una sonrisa que ilumina hasta el día más oscuro.",
  "¿Eres Google? Porque tienes todo lo que estoy buscando.",
  "Debes estar cansada, porque has estado corriendo por mi mente todo el día.",
  "¿Te puedo llevar a casa? Porque mamá me dijo que siguiera mis sueños.",
  "Si fueras una canción, serías mi favorita.",
  "No necesito Wi-Fi, porque ya estoy completamente conectado a ti.",
  "Tienes algo que me hace perder la razón, y creo que es tu sonrisa.",
  "¿Sabes qué? Tu sonrisa es mi lugar favorito.",
  "No necesito un GPS, ya que siempre me llevas directo a tu corazón.",
  "Contigo, las horas parecen minutos.",
  "Eres esa persona que hace que todo valga la pena.",
  "Si fueras un color, serías el arcoíris completo.",
  "Cada vez que te veo, me recuerdas lo hermosa que es la vida.",
  "Si ser guapa fuera un deporte, tú tendrías todas las medallas.",
  "No soy mago, pero cada vez que te veo, haces que todo lo demás desaparezca.",
  "Eres esa persona que hace que mi mundo sea un lugar mejor.",
  "Eres como mi canción favorita, no puedo dejar de escucharte.",
  "Si fueras una estrella, serías la que más brilla.",
  "Contigo, el mundo parece un poco más bonito.",
  "No hay palabras para describir lo increíble que eres.",
  "Cada vez que sonríes, mi corazón da un salto.",
  "Eres el motivo por el cual creo en el amor verdadero.",
  "Me haces sentir como si estuviera flotando en las nubes.",
  "Si fueras una película, querría verte una y otra vez.",
  "Eres el sueño del que no quiero despertar.",
  "Contigo, el tiempo simplemente vuela.",
  "Eres como un imán, no puedo evitar sentirme atraído por ti.",
  "Si fuera un semáforo, me pondría en rojo cada vez que pasaras, para verte un poco más.",
  "Eres como un buen libro, cuanto más te conozco, más quiero saber.",
  "Eres ese algo especial que hace que mi corazón lata más rápido.",
  "Cada vez que pienso en ti, mi día mejora.",
  "Eres tan especial que no sé cómo el mundo ha sobrevivido sin ti.",
  "Tu sonrisa tiene el poder de iluminar hasta el día más gris.",
  "Si las estrellas fueran tan brillantes como tú, el cielo no necesitaría la luna.",
  "Eres el café que me mantiene despierto en los sueños más bonitos.",
  "¿Sabes que tienes el poder de hacer que todo a tu alrededor desaparezca cuando sonríes?",
  "Eres el motivo por el que mi corazón late más fuerte cada día.",
  "Si el amor fuera un lenguaje, contigo sería bilingüe.",
  "Eres como un rayo de sol en un día nublado.",
  "Si fueras un perfume, te llevaría puesto todo el tiempo.",
  "Tu risa es mi sonido favorito en todo el mundo.",
]

crazy = [
  "Si fueras Wi-Fi, estarías protegida por contraseña porque eres demasiado buena para ser real.",
  "¿Eres una obra de arte? Porque no puedo dejar de admirarte.",
  "Si fueras un bolígrafo, estarías fuera de mi alcance porque eres demasiado fina para escribir en mi vida.",
  "Eres como el café, me mantienes despierto toda la noche.",
  "Si fueras un examen, te copiaría porque tienes todas las respuestas.",
  "¿Eres Google? Porque tienes todo lo que estoy buscando.",
  "Eres tan caliente que si fueras un helado, te derretirías antes de salir de la tienda.",
  "Si fueras pizza, serías la porción perfecta de mi vida.",
  "Eres como mi tarea de matemáticas: complicada pero vale la pena resolverte.",
  "Si fueras un Pokémon, te atraparía sin dudar.",
  "¿Eres un imán? Porque no puedo evitar sentirme atraído por ti.",
  "Si fueras una app, serías la más descargada en mi corazón.",
  "Contigo, el Wi-Fi nunca se cae porque siempre estoy conectado.",
  "Eres como Netflix, porque siempre quiero verte sin parar.",
  "Si fueras un refrigerador, te abriría cada 5 minutos solo para ver si sigues tan guapa.",
  "¿Eres un volcán? Porque cada vez que te veo, siento calor por dentro.",
  "Eres tan dulce que cada vez que te veo, siento que me da diabetes.",
  "Si fueras un virus, infectarías mi corazón sin antivirus.",
  "Eres como una alarma de incendio, porque cada vez que entras en la habitación, todos se ponen en alerta.",
  "Si fueras un semáforo, siempre estarías en verde porque me das luz verde para acercarme.",
  "Eres como el sol, porque haces que todo gire a tu alrededor.",
  "Si fueras un acertijo, serías el más difícil porque me dejas siempre pensando en ti.",
  "Eres como una hamburguesa con queso, algo que nunca puedo resistir.",
  "Si fueras una palabra en el diccionario, serías 'perfección'.",
  "¿Eres una estrella fugaz? Porque cada vez que te veo, hago un deseo.",
  "Eres como un tornado, porque me dejaste sin aliento desde que entraste en mi vida.",
  "Si fueras una receta, serías la más difícil, porque eres demasiado especial para seguir al pie de la letra.",
  "Eres como un cargador de teléfono: no puedo vivir sin ti.",
  "Si fueras un celular, serías el último modelo, porque todos querrían tenerte.",
  "¿Eres una cámara? Porque haces que todo a tu alrededor se vea increíble.",
  "Eres como la sal en la comida, sin ti todo es insípido.",
  "Si fueras una señal de tráfico, dirías 'Peligro: belleza inminente'.",
  "Eres como un control remoto: tienes el poder de cambiar mi estado de ánimo con solo un clic.",
  "Si fueras una película, serías mi maratón favorita de fin de semana.",
  "Eres tan brillante que el sol debería preocuparse por la competencia.",
  "Si fueras una bebida, serías el cóctel perfecto: irresistible y siempre refrescante.",
  "Eres como la batería de mi celular, cada vez que te veo, mi energía sube al 100%.",
  "Si fueras un libro, serías un bestseller, porque todo el mundo querría conocerte.",
  "Eres como un chocolate en verano: demasiado irresistible para durar mucho.",
  "Si fueras un sueño, no querría despertar nunca.",
  "Eres como una alarma, porque siempre me despiertas el interés.",
  "Si fueras un emoji, serías el corazón rojo porque siempre me enamoras.",
  "Eres como una conexión de fibra óptica: rápida, eficiente y haces todo mejor.",
  "Si fueras un videojuego, serías el nivel que nunca puedo superar.",
  "Eres como el aire acondicionado en verano, sin ti me derrito.",
  "Si fueras una tienda, te visitaría todos los días solo para verte.",
  "Eres como el Wi-Fi gratuito: todo el mundo te quiere, pero yo te quiero más.",
  "Si fueras una montaña rusa, no dejaría de subirme a ti.",
  "Eres como mi contraseña, porque sin ti no puedo acceder a la felicidad.",
  "Si fueras un meme, serías el más viral, porque todo el mundo habla de ti.",
]

es_flirts = {
  "normal": normal,
  "crazy": crazy,
  "all": normal + crazy,
}
