normal = [
  "Ton sourire illumine ma journée.",
  "Es-tu un magicien ? Parce que chaque fois que je te regarde, tout le reste disparaît.",
  "Si la beauté était un crime, tu serais en prison à vie.",
  "Est-ce que tu as un GPS ? Parce que je me perds dans tes yeux.",
  "Ton sourire devrait être interdit, il est trop captivant.",
  "Tu es comme le café, je ne peux pas me passer de toi.",
  "Est-ce que tu crois au coup de foudre ou dois-je repasser ?",
  "Si tu étais un fruit, tu serais une pêche, car tu es vraiment à croquer.",
  "Tu es si belle que tu fais de l’ombre aux étoiles.",
  "Es-tu fatiguée ? Parce que tu as couru dans mes pensées toute la journée.",
  "Je ne suis pas photographe, mais je pourrais nous imaginer ensemble.",
  "Avec toi, chaque jour est un jour de soleil, même quand il pleut.",
  "Est-ce que tu es Google ? Parce que tu as tout ce que je recherche.",
  "Tu devrais être illégale avec un sourire pareil.",
  "Es-tu un voleur ? Parce que tu viens de voler mon cœur.",
  "Si j'étais un chat, je passerais mes neuf vies à tes côtés.",
  "Tu es si douce que même le sucre semble fade à côté de toi.",
  "Je ne savais pas que les anges vivaient sur terre jusqu'à ce que je te rencontre.",
  "Est-ce que ça fait mal quand tu es tombée du ciel ?",
  "Avec toi, j'ai l'impression d'être dans un rêve dont je ne veux pas me réveiller.",
  "Ton rire est la plus belle mélodie que j’ai jamais entendue.",
  "Tu es tellement magnifique que tu fais de la lune une lumière de secours.",
  "Tu es comme une étoile, impossible de ne pas te remarquer dans le ciel.",
  "Tu es plus belle que toutes les fleurs de ce monde.",
  "Je pense à toi plus souvent qu’il n’y a de battements dans mon cœur.",
  "Es-tu un aimant ? Parce que je suis irrésistiblement attiré par toi.",
  "Si tu étais une chanson, tu serais la plus douce des mélodies.",
  "Tu es comme une œuvre d'art, chaque regard sur toi me fait découvrir quelque chose de nouveau.",
  "Je ne suis pas un génie, mais je sais que tu es mon vœu exaucé.",
  "Ton sourire est comme un rayon de soleil qui réchauffe tout sur son passage.",
  "J'ai l'impression que mon cœur fait des bonds chaque fois que tu es près de moi.",
  "Si j'avais un souhait, ce serait de passer chaque instant avec toi.",
  "Ton sourire pourrait faire fondre un iceberg.",
  "Je ne suis pas astronome, mais je sais que tu es la plus belle étoile de l'univers.",
  "Es-tu un dictionnaire ? Parce que tu donnes du sens à ma vie.",
  "Ton nom devrait être ajouté au dictionnaire à côté du mot 'perfection'.",
  "Je ne savais pas ce que signifiait la beauté avant de te rencontrer.",
  "Es-tu un rêve ? Parce que j'aimerais ne jamais me réveiller.",
  "Ton regard est plus brillant que toutes les étoiles du ciel.",
  "Chaque seconde avec toi est comme un instant volé au paradis.",
  "Je n’ai jamais cru aux contes de fées, jusqu'à ce que je te rencontre.",
  "Si l'amour était un sport, tu serais la médaille d'or.",
  "Si la vie est un jeu, tu en es le plus beau niveau.",
  "Ton sourire est comme un secret bien gardé, il mérite d'être révélé à tout le monde.",
  "Tu es mon coup de cœur au quotidien.",
  "Avec toi, je me sens comme le roi du monde.",
  "Chaque jour à tes côtés est une aventure dont je ne me lasse jamais.",
  "Si le bonheur avait un visage, il aurait le tien.",
  "Ton rire est plus précieux que tout l'or du monde.",
  "Es-tu un phare ? Parce que tu éclaires ma vie dans les moments les plus sombres.",
]

crazy = [
  "Si tu étais un fruit, tu serais un 'superbe-pêche'.",
  "Ton sourire est comme un antivirus, il protège mon cœur.",
  "Si j'étais un chat, je passerais mes neuf vies à te poursuivre.",
  "Es-tu un GPS ? Parce que je me perds dans ton regard.",
  "Si tu étais une chanson, tu serais celle que je veux mettre en boucle toute la journée.",
  "Tu es tellement belle que même le miroir est jaloux de toi.",
  "Ton regard est comme une potion magique, je suis sous ton charme.",
  "Si tu étais un film, je t’appellerais 'L'irrésistible charme'.",
  "Es-tu un ticket de loterie ? Parce que j’ai l’impression d’avoir gagné le gros lot.",
  "Ton rire est comme une alarme, il me réveille à chaque fois.",
  "Si tu étais une pizza, tu serais une 'extra-ravissante'.",
  "Tu es comme un bon café : fort, chaud et inoubliable.",
  "Es-tu une étoile ? Parce que tu fais briller ma nuit.",
  "Ton cœur est un trésor, et j’aimerais être le pirate qui le trouve.",
  "Si l’amour était une danse, tu serais ma partenaire parfaite.",
  "Es-tu un chocolat ? Parce que je suis accro à toi.",
  "Si j'étais un peintre, je te mettrais dans mon chef-d'œuvre.",
  "Ton odeur est plus enivrante qu'un parfum de luxe.",
  "Tu es comme un casse-tête : je ne peux pas te résoudre, mais je suis captivé.",
  "Si j'étais un astronautes, je passerais mes journées à explorer tes yeux.",
  "Tu es le mot de passe qui déverrouille mon cœur.",
  "Es-tu un bonbon ? Parce que je suis accro à ta douceur.",
  "Si la beauté était une crime, tu serais la reine du crime parfait.",
  "Ton amour est comme une montagne russe : excitant et à couper le souffle.",
  "Si tu étais une application, je te mettrais en favoris.",
  "Es-tu une créature mythique ? Parce que tu es vraiment unique.",
  "Ton charme est comme un aimant, je ne peux pas résister.",
  "Si j'étais un super-héros, tu serais mon super-pouvoir.",
  "Es-tu un feu d'artifice ? Parce que tu fais exploser mes émotions.",
  "Tu es comme un éclair au chocolat, un délice que je ne peux pas résister.",
  "Si l’amour était un plat, tu serais un délice gastronomique.",
  "Ton sourire est une pièce de puzzle qui complète ma vie.",
  "Es-tu un lapin ? Parce que tu fais battre mon cœur.",
  "Si tu étais une étoile filante, je ferais un vœu pour toi.",
  "Tu es comme un rêve, je ne veux pas me réveiller.",
  "Si tu étais un plat, tu serais le meilleur à la carte.",
  "Ton amour est comme un bon livre, je ne peux pas m’arrêter de le lire.",
  "Si j'étais un voleur, je volerais ton cœur.",
  "Es-tu un chameau ? Parce que tu es capable de me faire traverser le désert de la solitude.",
  "Ton rire est la mélodie que je veux écouter en boucle.",
  "Si tu étais un logiciel, tu serais la mise à jour que j'attends.",
  "Tu es comme un arc-en-ciel : rare et magnifique.",
  "Es-tu un souffle de vent ? Parce que tu apportes la fraîcheur dans ma vie.",
  "Si tu étais un gâteau, tu serais celui que tout le monde veut goûter.",
  "Ton regard est comme une boussole, il m'indique toujours le chemin vers toi.",
  "Es-tu un glacier ? Parce que tu es irrésistible et toujours frais.",
  "Si j'étais une abeille, je passerais mes journées à butiner ton amour.",
  "Ton charme est une tempête : inattendu et enivrant.",
  "Es-tu un phoque ? Parce que tu es trop mignonne.",
  "Si la vie était un jeu vidéo, tu serais mon niveau préféré.",
]

fr_flirts = {
  "normal": normal,
  "crazy": crazy,
  "all": normal + crazy,
}
