# Generated by Django 5.0.1 on 2024-10-13 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djx_account', '0004_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
