
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-13T21:43:59-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "e1f88446030dfb8b4b4cb4e6c6cb12a14d03787f",
 "version": "3.0.9.dev2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
