
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-10-11T11:46:28+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "f301c59bb96c3d610477d35791f65c9f54bb01a3",
 "version": "8.20.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
