# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/NamableClassify',
                'doc_host': 'https://2catycm.github.io',
                'git_url': 'https://github.com/2catycm/NamableClassify',
                'lib_path': 'namable_classify'},
  'syms': {'namable_classify.core': {'namable_classify.core.foo': ('core.html#foo', 'namable_classify/core.py')}}}
